### ISSUE TITLE
[1.10.2] Game crashes while launching

### ISSUE THREAD

**Issue by MasterFee** [Landmaster/PlusTiC#1]
Title pretty much explains everything. Game crashes when I try to launch it. Happened only after I install PlusTIC, so might be because of it. 

Here's the crash report:
http://pastebin.com/anysptn9

**Comment by Mike-T4** [comment]
I tried this with only TIC, and it still crashes. 
(And Mantle/TC of course since those are required)

**Comment by MasterFee** [comment]
So conflicts with any other mod can be excluded

**Comment by Mike-T4** [comment]
Tried it again, this time with Botania included. In the config, I disabled all integration besides Botania.
Still no luck. Also using Forge 18.3.2221.
Crash Report:
http://pastebin.com/gSD6yWbz

**Comment by Landmaster** [comment]
It turned out that the recipes for osmiridium and bronze nuggets were being registered even if they were not present! Testing for null items did the job.

**Comment by MasterFee** [comment]
So did you already update it?

**Comment by Landmaster** [comment]
Yes, it has been updated in the latest version.
