### ISSUE TITLE
[Suggestion] Thermal Foundation support

### ISSUE THREAD

**Issue by MasterFee** [Landmaster/PlusTiC#10]
Would be amazing if you could add TE support so we can have Signalum, Enderium, Lumium, etc. as materials. Like in the good old days in 1.7.10 with ExtraTiC.

**Comment by SynfulChaot** [comment]
I believe that would be called Thermal Foundation support, as the raw materials themselves are in Foundation rather than Expansion.

**Comment by HenryRichard** [comment]
While you're doing that, could you also look into adding support for Redstone Arsenal? I'd love to be able to charge my tools with RF power.

**Comment by Landmaster** [comment]
Signalum will be added in the next release.
