### ISSUE TITLE
[Request or Question] RF on tools

### ISSUE THREAD

**Issue by TheSnowyChickens** [Landmaster/PlusTiC#103]
Hello [First , sry for maybe bad english/grammar]

The creator from Tinkers remove the RF on tools and now I realize your mod has batteries for your weapons , but now the question , if you can add the batteries to the normal tools as RF modifier?

I would be appreciated it much , if you can add it. :)

Thx

**Comment by Landmaster** [comment]
Only the laser gun uses RF, and even then, it also uses durability. If, and when, I plan to add RF to Tinkers tools, it will probably be a trait on a high-tier material, rather than a modifier to be added to any tool. The RF modifier in older versions of TiC was *really* overpowered.
