### ISSUE TITLE
[Request]Enderman farm & TF missing alloy / metal

### ISSUE THREAD

**Issue by Thyriel** [Landmaster/PlusTiC#107]
Could you add the enderman farm ectraTic had ? So that endermans generate molten enderium instead blood when getting damage inside the smeltery

And support for Thermal Foundations Mana Infused metal and Constantan Alloy would be great.

**Comment by Landmaster** [comment]
- If I plan to make endermen produce a different fluid, it would be resonant ender, not molten enderium.
- Mana infused metal is just Mithril, which, if I am correct, is not used by TF at this time.
- Constantan is already added by Immersive Engineering.
