### ISSUE TITLE
Laser misses Ender Dragon

### ISSUE THREAD

**Issue by OneEyeMaker** [Landmaster/PlusTiC#110]
The title says it all: laser very often misses Ender Dragon.
It shows animation of shooting, plays sound and consumes energy, but Ender Dragon doesn't get any damage.
Maybe, cause of this is that Ender Dragon entity consists from multiple entities and laser attempt to damage wrong one.

MC 1.12.2 (but this occurs also on 1.10.2)
PlusTiC 6.3.1.2

**Comment by Landmaster** [comment]
When you are shooting at the Ender dragon, where was he? Also, try reproducing with only TiC, Mantle, and PlusTiC.

**Comment by OneEyeMaker** [comment]
Reproduce this behavior only with TConstruct (and it's dependencies) and PlusTiC is impossible, because there's no way to charge laser (even in creative).
After adding some mod with energy (Actually Additions/Thermal Expansion or any other) it can be simply reproduced with any laser.
Where is Ender Dragon when I'm shooting? It can be anywhere - from pedestal (portal) in center of End to far regions.
It can look like this: laser shoots but Dragon doesn't get any damage. (As you could see, damaged entity colored in red, but on these screenshots Dragon isn't.)
![2017-10-03_07 01 05](https://user-images.githubusercontent.com/14104815/31109586-95c1bd00-a809-11e7-85c8-66cc405e8196.png)
![2017-10-03_07 01 10](https://user-images.githubusercontent.com/14104815/31109587-95cd1e2a-a809-11e7-9282-2085585ec3d7.png)

**Comment by Landmaster** [comment]
Possibly related: SlimeKnights/TinkersConstruct#2861
