### ISSUE TITLE
New Katana texture

### ISSUE THREAD

**Issue by Tenebris11** [Landmaster/PlusTiC#112]
I decided to re-texture the katana if you are interested. :P
![binding](https://user-images.githubusercontent.com/11930600/31326536-4b448618-ac96-11e7-95c1-733faeb7e2a5.png)
![bottomblade](https://user-images.githubusercontent.com/11930600/31326537-4b493dd4-ac96-11e7-9168-9ca3e80a8863.png)
![handle](https://user-images.githubusercontent.com/11930600/31326539-4b4bff7e-ac96-11e7-82dc-5b783e053384.png)
![mod_beheading](https://user-images.githubusercontent.com/11930600/31326543-4b917e00-ac96-11e7-8bcf-ce5d1a757a0d.png)
![mod_diamond](https://user-images.githubusercontent.com/11930600/31326538-4b4bd15c-ac96-11e7-8728-c9e63f442b5a.png)
![mod_emerald](https://user-images.githubusercontent.com/11930600/31326540-4b4c2012-ac96-11e7-8d5b-5a1475ebdb31.png)
![topblade](https://user-images.githubusercontent.com/11930600/31326541-4b4ddc7c-ac96-11e7-9496-b431fff84613.png)
![topblade_broken](https://user-images.githubusercontent.com/11930600/31326542-4b54a1ba-ac96-11e7-904d-0c9fea6bb07b.png)

**Comment by Landmaster** [comment]
@Tenebris11 If you want to retexture the katana for PlusTiC, [make a pull request here with your changes.](https://github.com/Landmaster/PlusTiC/pulls)

**Comment by Tenebris11** [comment]
Ah, right.  It's been a while since I've used Github, sorry. :P

**Comment by Tenebris11** [comment]
First I'll also texture the gun as well.
