### ISSUE TITLE
Laser Gun texture spin + Laser bugs

### ISSUE THREAD

**Issue by Tenebris11** [Landmaster/PlusTiC#114]
Would you be willing to make the texture for the laser gun tilted so that it matches the way the IC2 laser and vanilla MC bow look like?  If so, I would have much more freedom with the texture and it would look nicer in your hand.  Additionally, I would like to mention that the laser for the gun seems to come from my  head and is attacking mobs through blocks.
![2017-10-09 3](https://user-images.githubusercontent.com/11930600/31347311-f0a14b3e-ace9-11e7-8956-0f671ca7135b.png)

**Comment by Tenebris11** [comment]
![2017-10-09 5](https://user-images.githubusercontent.com/11930600/31347398-3f08f7ae-acea-11e7-92d5-918fc3c17164.png)

**Comment by Tenebris11** [comment]
Never mind about the texture.  I'm stupid and forgot that I can just do that myself. *facepalm*

**Comment by Landmaster** [comment]
The laser attacking mobs through blocks is fine.
