### ISSUE TITLE
[1.12.2] Mining Level Tooltip

### ISSUE THREAD

**Issue by TheSnowyChickens** [Landmaster/PlusTiC#118]
Hello,

the mining Level tooltip from "Osgloglas" is just "5" and not like the other provided with a material name.
Is it possible to change this simple thing? All types only from Osgloglas have this little misstake with the Tooltip. :)

![2017-10-15_17 26 39](https://user-images.githubusercontent.com/29357962/31586193-3c1b5724-b1ce-11e7-930e-25ddee54396c.png)

MC 1.12.2
Forge 2512
TIC 2.7.4.34
PlusTIC 6.3.1.2

**Comment by Landmaster** [comment]
This is because it has a higher mining level than vanilla Tinkers materials. [Use a resource pack if you want to add text for high mining levels.](https://github.com/SlimeKnights/TinkersConstruct/wiki/Overwriting-Harvest-Levels)

**Comment by TheSnowyChickens** [comment]
Hello again,

I think the harvest level post from you : "Use a resource pack if you want to add text for high mining levels." no longer works, because : 

##################
#   UI Strings   #
##################
# general strings used in GUIs, tooltips and other display stuff

ui.mininglevel.0=§7Stone
ui.mininglevel.1=§fIron
ui.mininglevel.2=§dDiamond
ui.mininglevel.3=§1Obsidian
ui.mininglevel.4=§9Cobalt
ui.mininglevel.5=§5Manyullyn
ui.mininglevel.6=§6Unobtanium

don't overwrite it. :(  (The other points 0-5 work)

![hl5](https://user-images.githubusercontent.com/29357962/34463989-7f1d53c4-ee6e-11e7-9608-6e46b2fbef22.png)

The resourcepack with the text above is installed, have you any ideas how it work now? Or am I doing something wrong?
