### ISSUE TITLE
[1.10.2][Galacticraft] Molten Desh cannot be turned into a block

### ISSUE THREAD

**Issue by BrisingrAerowing** [Landmaster/PlusTiC#121]
As per title. In 1.10.2 Molten Desh cannot be turned into a block with a casting basin. The basin shows 0 / 0 Molten Desh, so I think there is a recipe error somewhere.

**Comment by Landmaster** [comment]
Does Galacticraft oredict its Desh Block correctly into `blockDesh`?

**Comment by BrisingrAerowing** [comment]
It would seem that they don't. I'll raise an issue about that.

**Comment by BrisingrAerowing** [comment]
They do no. I'll raise an issue with the project.
