### ISSUE TITLE
not compatible with modern metals.

### ISSUE THREAD

**Issue by gruvarbetare0** [Landmaster/PlusTiC#124]
I'm playing on minecraft version 1.11.2. I'm using plus tic version 5.2.1.2, and the game crashes everytime I load using the modern metals mod. If I disable modern metals, it loads fine with plus tic. If I disable plus tic, it loads fine with modern metals. I've attached both mod files here for reference.
[mods.zip](https://github.com/Landmaster/PlusTiC/files/1435334/mods.zip)

Edit: Here's the crash report:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PlusTiC (plustic)
[crash-2017-11-01_11.46.53-client.txt](https://github.com/Landmaster/PlusTiC/files/1435353/crash-2017-11-01_11.46.53-client.txt)

**Comment by Landmaster** [comment]
Disable either LandCore integration on PlusTiC or Tungsten on Modern Metals.
