### ISSUE TITLE
Missing materials

### ISSUE THREAD

**Issue by zachg86** [Landmaster/PlusTiC#126]
Hello,

I can't seem to get some of the vanilla TiC/PlusTiC materials to appear in-game - notably, alumite and electrum.  I'm running version 1.10.2, and I've tried various versions of Forge.  I've tried both PlusTiC 5.2.1.1 and 5.2.1.2, with TiC 2.6.5, CompatLayer 0.2.9, and Mantle 1.1.5.

I've tried reading around the existing comments on the CurseForge page, as well as the closed issues, and haven't really been able to find anything.  I didn't see anything about alumite being removed, either, and I've tried to check the various release notes for TiC and PlusTiC.  Any ideas, or was alumite not present in these PlusTiC versions?

Thanks!

**Comment by Landmaster** [comment]
You need to have other mods that add the required metals: aluminum for alumite, and silver for electrum.

**Comment by zachg86** [comment]
I apologize, I forgot to add - I also tried with Base Metals 2.4.0.11 and MMD Ore Spawn 1.1.0.

Thank you for the fast response!

**Comment by zachg86** [comment]
You know what, after looking more closely, it looks like Base Metals doesn't include Aluminum.  Thanks again!
