### ISSUE TITLE
Crash due to a java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by dmodoomsirius** [Landmaster/PlusTiC#129]
https://gist.github.com/dmodoomsirius/e8afbb2662a98ce9dcdbe0c59ce97203

**Comment by Landmaster** [comment]
Steps to reproduce?

**Comment by Landmaster** [comment]
Closing because this appears to be the fault of a coremod that is completely unrelated to PlusTiC and its dependencies.
