### ISSUE TITLE
Crash On start

### ISSUE THREAD

**Issue by YOYOK9** [Landmaster/PlusTiC#13]
Getting a crash on client start. Using the latest version of Plastic. plustic-3.0a. But it seems fine with 3.0. Seems to be having troubles with the new cofh mods.

Report: http://pastebin.com/bQRVJe3Q

**Comment by Doomathon** [comment]
Can confirm that I had this crash when testing 3.0a.

Crash log: http://pastebin.com/nd66QPsH

**Comment by Jacky1356400** [comment]
Same here, seems fine after disabling Thermal Foundation integration in PlusTiC config.
