### ISSUE TITLE
[1.12.2] Crash with new TiC version

### ISSUE THREAD

**Issue by JonasCiss** [Landmaster/PlusTiC#131]
The game crashes with the latest version of TiC.
[crash-2017-12-09_02.15.53-client.txt](https://github.com/Landmaster/PlusTiC/files/1544243/crash-2017-12-09_02.15.53-client.txt)
[crash-2017-12-09_02.18.04-client.txt](https://github.com/Landmaster/PlusTiC/files/1544244/crash-2017-12-09_02.18.04-client.txt)

**Comment by TheOldOne822** [comment]
It's a conflict with a new trait added to base TiC.

**Comment by aldra2012** [comment]
is there a work around? or do we have to wait for an update?

**Comment by EmosewaGamer** [comment]
@aldra2012 nope, you have to wait for an update.

**Comment by JonasCiss** [comment]
I think an update wouldn't last long. Or it is a big change?

**Comment by JonasCiss** [comment]
I got this crash after I had only changed the TiC version.

**Comment by aldra2012** [comment]
@SirTwsted  yeah its the same crash i got, just downgrade tinkers until a update for plustic comes out

**Comment by Landmaster** [comment]
Same issue as #133
