### ISSUE TITLE
Dangerous alternative prefix

### ISSUE THREAD

**Issue by trilexcom** [Landmaster/PlusTiC#132]
hi Landmaster / PlusTIC team

i am getting this error msg in console

KnightMiner from TContruct told me open a issue with you we were getting the same issue with jackys mod jacky market it bug 

https://github.com/Jacky1356400/IntegrationForegoing/issues/12

https://github.com/SlimeKnights/TinkersConstruct/issues/3268

so i thought i would report this issue to you too

this is what he says (KnightMiner)

This looks like integrationforegoing's fault, they are accessing our traits before we have a chance to register the potions (thus it is reigstered during their time). Report the issue to that mod's author.

@bookerthegeek we do not register anything into the Minecraft domain, potions are registered under TConstruct.
****************************************
--
03:54:09 | FML | main | warn | * Dangerous alternative prefix `tconstruct` for name `enderference`, expected `plustic` invalid registry invocation/invalid name?
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitEnderference.<clinit>(TraitEnderference.java:18)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:72)
03:54:09 | FML | main | warn | *  at landmaster.plustic.modules.ModuleBase.init(ModuleBase.java:82)...
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | * Dangerous alternative prefix `tconstruct` for name `insatiable`, expected `plustic` invalid registry invocation/invalid name?
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitInsatiable.<clinit>(TraitInsatiable.java:13)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:78)...
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | * Dangerous alternative prefix `tconstruct` for name `magnetic`, expected `plustic` invalid registry invocation/invalid name?
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitMagnetic$MagneticPotion.<init>(TraitMagnetic.java:46)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitMagnetic.<clinit>(TraitMagnetic.java:25)...
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | * Dangerous alternative prefix `tconstruct` for name `momentum`, expected `plustic` invalid registry invocation/invalid name?
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitMomentum.<clinit>(TraitMomentum.java:18)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:83)...
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | * Dangerous alternative prefix `tconstruct` for name `dot`, expected `plustic` invalid registry invocation/invalid name?
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitSharp$DoT.<init>(TraitSharp.java:51)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitSharp.<clinit>(TraitSharp.java:18)...
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | ****************************************
03:54:09 | FML | main | warn | * Dangerous alternative prefix `tconstruct` for name `splinter`, expected `plustic` invalid registry invocation/invalid name?
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
03:54:09 | FML | main | warn | *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:20)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.library.potion.TinkerPotion.<init>(TinkerPotion.java:13)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.traits.TraitSplintering.<clinit>(TraitSplintering.java:14)
03:54:09 | FML | main | warn | *  at slimeknights.tconstruct.tools.TinkerTraits.<clinit>(TinkerTraits.java:92)...
03:54:09 | FML | main | warn | ****************************************

We are using Forge 2556
TinkersContruct Version : TConstruct-1.12-2.7.4.34
PlusTick Version :  plustic-6.3.2.0
MC : 1.12.2
Crashlog : https://pastebin.com/NWMF4wvg

Thanks

Mat

**Comment by Landmaster** [comment]
This is not really an issue; the way that PlusTiC accesses the traits is intentional.
