### ISSUE TITLE
Crash with PlusTIC v6.3.2.0

### ISSUE THREAD

**Issue by SirTwsted** [Landmaster/PlusTiC#133]
java.lang.ExceptionInInitializerError
and
net.minecraftforge.fml.common.LoaderExceptionModCrash

Minecraft v1.12.2
Tinkers Construct v2.8.0.45
PlusTIC v6.3.2.0
Forge v14.23.1.2555

**Further down the crash log it says this:**
**Caused by:** slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Trying to register a modifier with the name heavy but it already is registered

https://pastebin.com/MyYWfWLs

**Comment by trilexcom** [comment]
here too crashlog : https://pastebin.com/RvUuEuvP

Forge : 2562

**Comment by BrewAndCode** [comment]
does anyone know which material in plusTic gives the heavy attrib?  Going to try to disable that attribute in the config.

**Comment by BrewAndCode** [comment]
bah, no joy.  Oh well.  Guess we shall wait.

**Comment by grydian** [comment]
I searched the code here on github and I believe the two metals in question are platinum and tungsten.  I am going to disable those two in the config and see if works.  Will report in a moment.

**Comment by BrewAndCode** [comment]
I already did that.. that just keeps the trait from being registered to that material but the trait itself is still being instantiated, which is causing the crash.  It really just needs to be renamed.

**Comment by grydian** [comment]
Gotcha.

**Comment by BrewAndCode** [comment]
I'm going to submit a pull and see if Landmaster takes it.  The pull request may get his attention.

**Comment by BrewAndCode** [comment]
yay! thix
