### ISSUE TITLE
BoP integration - Flamestring

### ISSUE THREAD

**Issue by vrork** [Landmaster/PlusTiC#135]
I noticed that the Flamestring (the one that drops from the fire spiders from the BoP nether) have no integration. If i renember well, in 1.7.10, i think iguana (or vanilla tinkers) had them compatible, making better strings than the vanilla. Any chances of them being added?

**Comment by belathus** [comment]
Heatscar Spiders and the flamestring are from Natura. I know that Natura's issue tracker still recommends disabling the heatscar spiders and keeps them disabled by default due to some unresolved bugs. Maybe that is why PlusTiC doesn't support it yet?
