### ISSUE TITLE
Weird tooltips?

### ISSUE THREAD

**Issue by Jerria1** [Landmaster/PlusTiC#136]
The tool-tips in my game are all messed up, they say something like "null.plustic.material" not sure if this is a bug for everyone or if its just for me.

**Comment by Landmaster** [comment]
Do you have a screenshot?

**Comment by Jerria1** [comment]
![2017-12-25_23 14 06](https://user-images.githubusercontent.com/34838722/34361715-58352754-ea32-11e7-935d-ce584aefef40.png)

**Comment by Jerria1** [comment]
I think it might be a conflict with Tinkers Defense

**Comment by AugiteSoul** [comment]
Ah yeah, Tinker's Defense has very WIP stuff, like materials. Not PlusTiC related, maybe close it?

**Comment by Landmaster** [comment]
Strange. Purified Silver is not implemented in PlusTiC. Is this only for the katanas and laser guns?

**Comment by Jerria1** [comment]
Any material added by Tinkers Defense
