### ISSUE TITLE
1.12.2 PlusTiC 6.3.2.1 Unable To Swap Tool Parts (TiCon 2.8.1.49)

### ISSUE THREAD

**Issue by ArticulatedDrunk** [Landmaster/PlusTiC#138]
When I try to swap out the head of the pickaxe head it says "Error Not enough Modifiers. (1 needed)"
I have the tinkers tool leveling addon installed, doesn't seem to be a problem with them.
I also have the plustic addon, might be a problem with them.
The pickaxe is a wooden tool rod with a stone binding and stone pickaxe head.
Current traits are: Ecological, Cheapskate, Cheap, Diamond, Luck III (360/360), Haster (100/100), with 3 additional modifiers. I am trying to swap in an obsidian pickaxe head. (For the record I can't seem to swap in any other part either.)
![image](https://user-images.githubusercontent.com/22388690/34508772-6a6bfa64-f000-11e7-81b9-f7f6c65254bc.png)
![image](https://user-images.githubusercontent.com/22388690/34508775-75a7abc6-f000-11e7-89e7-e3a7e6716f27.png)
I will post this on both the plustic and Tinkers Construct githubs.
https://github.com/SlimeKnights/TinkersConstruct/issues/3317
If any other information is needed let me know and I will get back to you as soon as possible.

**Comment by Landmaster** [comment]
Try testing with only Mantle and Tinkers Construct. Then, try testing with only Mantle, Tinkers Construct, and PlusTiC.

**Comment by ArticulatedDrunk** [comment]
I can change the parts on freshly made tools. I'm not quite sure how to replicate this though. Is the a console command to set the xp level?

**Comment by ArticulatedDrunk** [comment]
Another thing I forgot to mention. It seems like tinkers still does the thing where repairing slowly degrades every time you do it. I excavated an extremely large area with this. It's a stone tool. I repaired it probably at least 100 times.

**Comment by ArticulatedDrunk** [comment]
With just tinkers I cannot seem to replicate it.
![image](https://user-images.githubusercontent.com/22388690/34546566-ed3ce096-f0b1-11e7-95fa-8388ef6b6bdc.png)

**Comment by ArticulatedDrunk** [comment]
Welp shit. My bad guys, I wasted your time. This appears to be a known issue.
https://github.com/SlimeKnights/TinkersToolLeveling/issues/31
