### ISSUE TITLE
Item lost all data for materials and modifiers (1.10.2 in Project Ozone Lite modpack)

### ISSUE THREAD

**Issue by Sarelth** [Landmaster/PlusTiC#142]
I made a pickaxe, Carbon Head, upgraded the binding to Emerald and the Tool rod to Infinity.

Item turned white at one point and has lost all stats and has 1 durability. Not sure what happened exactly.
It did get put in a Wireless Crafting ME Terminal for a short period, unintentionally. This may have been the cause, not sure though.

**Comment by Sarelth** [comment]
I think I figured out part of the issue. It appears that the Extra Utilities Search for Iems nearby Inventories ability is bugged in some way. It makes the item become a generic, statless object and if moved into certain areas, ie the wireless crafting terminal crafting grid, it can cause weird results.

**Comment by Landmaster** [comment]
Normally, I would say to report this to Extra Utilities, but the only problem with doing so is that Extra Utilities' creator does not seem to pay very much attention to his issue tracker. Given that you used a Carbon head (which is not added by PlusTiC), I would suggest that you figure out what mod adds Carbon, and open this issue on that mod's side as well. This looks like a mod interaction issue.

Also, try reproducing the issue with only Mantle, Tinkers Construct, PlusTiC, and whatever mod adds Carbon.

**Comment by Sarelth** [comment]
I think it has more to do with Extra utilities after some testing. I reproduced it with other materials and other items not related to tinkers or Plustic.

Seems somehow related to the extra utilities search for items in nearby inventory and wireless terminal and bad timing.
