### ISSUE TITLE
Laser Gun Smelting Causing Duplicate Drops

### ISSUE THREAD

**Issue by MoonBunnie** [Landmaster/PlusTiC#144]
Holding down the "fire" button while in smelting mode will cause the game to permanently double the products of recipes until a server restart.

Example:
1. Place down a row of N number Birch Logs.
2. Press and HOLD the smelt button to smelt the row of blocks.
3. Notice that the Nth block smelted will drop 2^(N-1) number of charcoal. (ex: 1, 2, 4, 8, etc)
4. Place a Birch Log in a vanilla furnace and notice that the furnace also produces extra charcoal based on what value of N was reached.
5. Restart server.
6. Notice that furnaces now produce 1 charcoal again and smelting (without holding the button) will go back to producing 1 charcoal per block again.

Seems to affect that specific smelting recipe permanently across all machines/tools that use that recipe. Each item type is affected individually (causing duplicate drops for charcoal does not affect the amount of glass drops from sand, but the steps can be repeated to force duplicate glass drops from sand)

Using Modern Skyblock 2 modpack if that helps at all.

**Comment by Landmaster** [comment]
Try reproducing with only Mantle, Tinkers Construct, PlusTiC, and one mod that adds a recharger (e.g. Mekanism).

**Comment by Landmaster** [comment]
Also, does this issue appear in 1.11 also?

**Comment by Landmaster** [comment]
Fixed in 6.3.3.0
