### ISSUE TITLE
Pink Slime from Industrial Foregoing not recognized for tool parts

### ISSUE THREAD

**Issue by dash16** [Landmaster/PlusTiC#145]
Industrial Foregoing is the MineFactory Reloaded replacement for 1.12.  It has Pink Slime just like MFR does, however I can't cast any parts using the Smeltery and liquid Pink Slime.  I can see the Pink Slime tinker parts in JEI, however there doesn't seem to be a way to create them in game.

Place 3 buckets of Pink Slime in the Smeltery, put a Tough Tool Rod Cast into a Casting Table, try to pour from a faucet into the cast, no go.  Slime pours fine into a tank.

TConstruct-1.12.2-2.9.0.55
Mantle-1.12-1.3.1.21
plustic-6.3.2.1
industrialforegoing-1.12.2-1.7.0-114
Forge 1.12.2 - 14.23.1.2590

**Comment by Landmaster** [comment]
This will be added next version.
