### ISSUE TITLE
Global Traveller issue

### ISSUE THREAD

**Issue by CriticalMole** [Landmaster/PlusTiC#15]
When having a pick linked to a chest via global traveller and the chest is full we are finding that while ores and the like are dropping on the ground, other items like ExU2 generators are poofing out of existence when broken.
Not sure if there is anything I can do to resolve this or if it is a full on bug for you guys

**Comment by Landmaster** [comment]
The fact that only some items are being affected by this bug is very unusual indeed. I'll see what I can do to fix this, but given that ExU2 is closed source, this will certainly not be easy to fix.

**Comment by CriticalMole** [comment]
If I notice any other blocks that are affected I will be sure to let you know

**Comment by Jo-Mamma75** [comment]
Additionally, we've had a few server crashes on iskall85's Patron servers related to this same issue.
Here is a pastebin of the most recent crash.  Not sure if that will help with your troubleshooting.
https://pastebin.com/KvFe9NDZ

**Comment by Jo-Mamma75** [comment]
Just did some additional testing with this.  I'll spare you the details but it boiled down to something is wrong with the player's specific pick axe.  Copied the pick in creative mode and the copied version seems to work fine.  Compared the pick axes in the player's inventory with NBTExplorer and no differences were spotted.
Again, don't know if that helps you at all but it might.

**Comment by Landmaster** [comment]
@Jo-Mamma75 I think I figured out why it is crashing on the server. It seems like some random mod is setting their drops to an immutable list, while Global Traveler requires the list to be changed in order for it to work. Unfortunately, there is not much that I can do about this, since the list reference in the harvest drops event is final, but I'll see if I can somehow use java reflection to overcome this.

**Comment by Jo-Mamma75** [comment]
Thanks.  I/we appreciate you looking into it for us.  Just wanted to mention that I tried "copying" another players pick on one of our servers last night and this time it did NOT work.  Server crashed as soon as he tried mining the machine.  Not that this new information helps much.  It sounds like you already have a pretty good idea of what's causing it.
Thanks again for looking into it and let us know what you find out.

**Comment by Landmaster** [comment]
I'm working on a class transform override as a possible workaround for this. It's pretty ugly, though.

**Comment by Landmaster** [comment]
I think I've got my fix working somewhat. (It requires CodeChickenLib, though.) I'll test it some more just to make sure, but once I have got everything working, I can declare this issue resolved.

**Comment by Landmaster** [comment]
I'll reopen this issue if more problems persist, but for the time being this issue has been fixed in the dev version.
