### ISSUE TITLE
[Mod Compat - Crash] Tweaker's Construct and Diamatine

### ISSUE THREAD

**Issue by ElvenChaos** [Landmaster/PlusTiC#154]
When using [Tweaker's Construct](https://minecraft.curseforge.com/projects/tweakers-construct) to edit Act Adds. diamatine, TwkCon throws an NPE and crashes on start.

[Crash Log](https://gist.github.com/ElvenChaos/ed5bdfd1df59137edabfe33bc5cffec9)
[TwkCon Config](https://gist.github.com/ElvenChaos/5b575dbd3e9a9a5f8c31fbae9f2a4f84)
Offending Config Line: `diamatine_actadd_plustic:d:d:d:3:d:d:d:d:d:d`

_Note: While I do have multiple entries in the relevant config, I did previously narrow down the crashing material to diamatine before posting._

Issue on TwkCon repository: https://github.com/RCXcrafter/TweakersConstruct/issues/1

**Comment by Landmaster** [comment]
This is a Tweaker's Construct issue; [they fail to check if a particular set of stats are deliberately not implemented for a material.](https://github.com/RCXcrafter/TweakersConstruct/blob/master/src/main/java/com/rcx/tweaconstruct/tweaks/StatTweaks.java#L37-L45)

**Comment by RCXcrafter** [comment]
Yep, didn't realise you could do that, a fix is on the way.
