### ISSUE TITLE
[Request] Integrate Vanilla Diamonds

### ISSUE THREAD

**Issue by ElvenChaos** [Landmaster/PlusTiC#155]
Diamond are all lonely in tcon tools, especially with his brother Emerald getting all the new toys, and his son Diamatine learning how to become tools. Diamonds reminisces about the old vanilla tool days where he was a normal diamond pickaxe.

Temporary Workaround:
[Infini-TiC](https://minecraft.curseforge.com/projects/infini-tic) allows the implementation of any material with custom-defined stats and any modifier that currently exists in the pack.

**Comment by Landmaster** [comment]
No: diamond would simply burn into carbon dioxide, and even if it could be melted, it would most likely solidify into graphite under standard conditions.

**Comment by ElvenChaos** [comment]
You don't have to melt it, I agree that molten diamond doesn't make sense. It could be an optional part that is craftable in the part builder. You've implemented Act. Adds. Diamatine, which is a diamond with a laser ran through it. You also didn't make a molten metal out of it, which is fine. You also implemented every single gem from BoP and Act. Adds., as well as emeralds from vanilla/tcon. I get that it may not seem realistic to have parts made purely of diamond, that diamonds are better used for edges than bodies, but it is something done in-part by both vanilla minecraft and PlusTiC. Part-built diamond parts make as much sense as these additions, if not a smidgen more as it is the only tool-part used to craft vanilla tools that isn't represented between TCon and PlusTiC.

Just like other PlusTiC materials, it could still be toggled by config as well.

**Comment by Landmaster** [comment]
The problem is that diamond and emerald tend to correspond more to each other (because they are vanilla items) than to the BoP or Act. Add. gems. For both this reason and the lack of demand for diamond tools, I have purposely left Diamond out.
