### ISSUE TITLE
Illuminati glow blacks out screen

### ISSUE THREAD

**Issue by makeshiftwings** [Landmaster/PlusTiC#158]
The Illuminati effect from materials like Refined Glowstone says it "causes nearby entities to glow", but in my case it turns the entire screen completely black except for entities, which are white. Is this intended? I'm guessing that's not intended. I'm using Optifine but no shaders or particularly weird render settings.

**Comment by Landmaster** [comment]
@makeshiftwings Do you have a screenshot?

**Comment by Landmaster** [comment]
Closing due to lack of information.
