### ISSUE TITLE
[1.12] compataility with enderio

### ISSUE THREAD

**Issue by jmac460** [Landmaster/PlusTiC#159]
https://hastebin.com/peqitotate.sql

Error occurs with Compatability with EnderIO

**Comment by BrisingrAerowing** [comment]
More Info:

This occurs with the new Ender IO testing releases for 1.12. They can be found [here](http://mc.joduwei.com/).  Ender IO split into multiple submods, which is the main cause of this (package names have changed). They are also working on their own TiC compatibility module.

**Comment by trilexcom** [comment]
if you go in the plustic config file and disable enderio compatibility plustic should work fine for now i tested i had the same issue, 

[crash-2018-02-21_00.48.10-client.txt](https://github.com/Landmaster/PlusTiC/files/1742987/crash-2018-02-21_00.48.10-client.txt)
