### ISSUE TITLE
Compatibility issue/crash with Aroma1997's Dimensional World

### ISSUE THREAD

**Issue by carstorm** [Landmaster/PlusTiC#161]
If you mine Sticky Ore from the mod Aroma1997's Dimensional World while you are using a tool that has the Global Traveler trait you will crash a dedicated server if playing multiplayer, or client if playing single player. 

https://pastebin.com/X6Uk2tgV

**Comment by Landmaster** [comment]
This is an Aroma1997's Dimensional World issue; [they are not implementing block drop overrides correctly. (Although the linked post mentions ExU2, the same issue is present with Aroma1997's mod as well.)](https://github.com/Landmaster/PlusTiC/issues/149#issuecomment-362103248)
