### ISSUE TITLE
null fluid stack with enderio

### ISSUE THREAD

**Issue by Seth0067** [Landmaster/PlusTiC#164]
I am using plustic with a 1.12 text build of enderio, but wanted to share this with you as i am sure you would want to resolve issue with this mod:
[pastebin crash report](https://pastebin.com/6qsFVgJb)

The build I am running is the nightly 229 build.  Plustic was fuctioning properly before I added enderio.
[Enderio test builds](https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/229/)

**Comment by Landmaster** [comment]
duplicate of #159
