### ISSUE TITLE
1.12 Strange interaction of tool traits

### ISSUE THREAD

**Issue by Spazley** [Landmaster/PlusTiC#165]
There is a crash when using Portly Gentleman.  I have enderium on a shuriken that I use in my off hand.  I only remember it happening when the tool I have in my main hand has enderium but not portly gentleman, though that may be irrelevant. It's happened at least with mobs from Primitive Mobs and Abyssalcraft.  In my attempts to replicate it, the only thing that seemed to be consistent was the combination of tools in the two hands, although that didn't always produce a crash.

PlusTiC 6.3.6.2

The crash report:  https://pastebin.com/D7rqRnCh

**Comment by Landmaster** [comment]
What traits are on each tool?

**Comment by Spazley** [comment]
Shuriken: Prosperous, Duritae, Insatiable, Cold-Blooded, Portly Gentleman, Global Traveler, Enderference, Endspeed, Elemental, Terrafirma, Unbreakable, Sharpestest, Hearts
(Supremium-Manyullyn-Enderium-Emerald & Embossed Restonia)

Broadsword: Global Traveler, Enderference, Prosperous, Duritae, Hearts, Luck III, Sharpestest, Hastestest
(Supremium blade, Enderium handle, Restonia guard)

**Comment by Landmaster** [comment]
Try reproducing with the minimum amount of traits.

**Comment by Spazley** [comment]
I probably should have included that this is on Forever Stranded Lost Souls.

After narrowing down the actions and mods included, the crash happens when the mob was just damaged by the tool and Tinkers' Tool Leveling is present. I was able to reproduce it even when Portly Gentleman was the only trait on the tool.

**First:**
Offhand: Broadsword: Supremium blade, Enderium guard, Supremium handle (Prosperous, Duritae, Global Traveller, Enderference)
Mainhand: Shuriken: 3 Enderium blades and 1 Supremium blades (Properous, Duritae, Portly Gentleman, Global Traveler, Enderference, Endspeed)
I didn't reproduce it until after repairing the shuriken and damaging the mob. The mob was a spore creeper from NetherEx. 

**Second:**
Offhand: Broadsword: Supremium blade, Enderium guard, Supremium handle (Prosperous, Duritae, Global Traveller, Enderference)
Mainhand: Shuriken: 4 Fluix Crystal blades (Portly Gentleman)
Picked up a spore creeper with no issue. Placed it back. Repaired the Shuriken. Picked up again with no issue. Placed it back. Damaged it using the shuriken. Tried to pick up again and crashed.

**Third:**
Offhand: Nothing
Mainhand: Shuriken: 4 Fluix Crystal blades (Portly Gentleman)
Tried to pick up a blaze. Didn't have enough durability. Repaired. Picked up blaze. Placed blaze back. Damaged it using the shuriken. Tried to pick it up again and it crashed.

**Fourth:**
Offhand: Nothing
Mainhand: Shuriken: 4 Fluix Crystal blades (Portly Gentleman)
New shuriken. Damaged a brown mogus from NetherEx using the shuriken. Tried to pick it up and crashed.

**Fifth:**
Offhand: Nothing
Mainhand: Rapier: Full Fluix Crystal (Portly Gentleman)
Picked up a brown mogus no problem. Placed it back. Damaged the brown mogus with the rapier. Tried to pick it up and crashed.

**Sixth:**
Offhand: Nothing
Mainhand: Rapier: Full Fluix Crystal (Portly Gentleman)
Picked up a zombie pigman no problem. Placed it back. Picked it up with a mob imprisonment tool from Industrial Foregoing to look at the NBT data. Placed it back. Hit it with the rapier. Picked it up again to look at the NBT data to see if anything changed. 35 NBT tags both times — I'll look at them closer or give them to you if think it's important. Placed it back. Tried to pick it up with the rapier. It _did not_ crash this time. Hit it with the rapier. Tried to pick it up and it _did_ crash.

-----

New Minecraft instance with limited mods to see if the problem persists: CoFH Core, CoFH World, JEI, Mantle, PlusTiC, Redstone Flux, Thermal Foundation, Tinker I/O, Tinkers Construct, Tinkers' Addons Tinkers' Complement, Tinkers' Tool Leveling.
These mods were picked to only have necessary mods for enderium parts and to have all the Tinkers mods that are present in Forever Stranded Lost Souls.

**Seventh:**
Offhand: Nothing
Mainhand: Broadsword: Full Enderium (Global Traveler, Enderference, Portly Gentleman)
Picked up a cow no problem. Damaged it. Tried to pick it up and crashed.

-----

Disabled Tinker I/O, Tinkers' Addons, Tinkers' Complement, Tinkers' Tool Leveling

**Eighth:** _No crash_
Offhand: Nothing
Mainhand: Broadsword: Full Enderium (Global Traveler, Enderference, Portly Gentleman)
Picked up a cow with no problem even after having just attacked it with the broadsword.

-----

Re-enabled Tinkers' Addons

**Ninth:** _No crash_

-----

Disabled Tinkers' Addons. Enabled Tinkers' Tool Leveling.

**Tenth:**
Offhand: Nothing
Mainhand: Broadsword: Full Enderium (Global Traveler, Enderference, Portly Gentleman)
Picked up a cow no problem. Damaged the cow. Tried to pick it up and crashed.

**Eleventh:**
Offhand: Nothing
Mainhand: Broadsword: Full Enderium (Global Traveler, Enderference, Portly Gentleman)
Picked up the cow no problem. Damaged with wooden sword. Picked up the cow no problem. Damaged a cow with a stone broadsword (cheapskate, cheap). Picked it up no problem with the enderium broadsword. Damaged a cow with an enderium rapier. Picked it up no problem with the enderium broadsword. Damaged a cow with an enderium rapier. Tried to pick it up with the enderium rapier and crashed.

**Twelfth:**
Offhand: Nothing
Picked up a cow with an enderium rapier no problem. Damaged it with the same rapier. Picked it up with a different enderium rapier no problem. Damaged a cow with the second rapier. Tried to pick it up with the second rapier and crashed.

**Thirteenth:**
Offhand: Nothing
Two new enderium rapiers. Damaged cow with the first. Picked it up with the second no problem. Damaged a cow with the second. It hit a cactus and took damage. Picked it up with the first no problem.
Two new enderium rapiers. Damaged cow with the first. Picked it up with the second no problem. Damaged a cow with the second. Tried to pick it up with the first and crashed.
This is being done in creative, so the only way the tools are being damaged is if they successfully pick up a mob. The lack of a crash after the cow was damaged by a cactus (as well as the other crashes) makes me think that it's somehow related to the NBT data telling the last cause of damage to the mob, but that's just speculation on my part.

In case it's relevant, the Tinkers' Tool Leveling version is 1.0.3
Let me know if there is any other information you want or any other testing needed.

**Comment by bonii-xx** [comment]
Heh. I know what's going on, and of course it's really stupid. ToolLeveling saves which item hurt the entity to distribute the xp accordingly on death. Portly Gentleman saves the entity inside the tool. Now when you first hurt the entity, the tool gets saved on the entity. Then you capture the entity which is saved in the tool.. which contains the tool that hurt it.. which now contains the entity that is being captured.. which contains the tool that hurt it... yay.

**Comment by bonii-xx** [comment]
I broke up the recursion by splitting the NBT instances in https://github.com/SlimeKnights/TinkersToolLeveling/commit/f525fdabdd439e054098b1305b7488ccf8473997

Should be fine with TTL 1.0.4
