### ISSUE TITLE
EnderIO crash 1.12

### ISSUE THREAD

**Issue by Staegrin** [Landmaster/PlusTiC#171]
Intalled:
JEI
Ender IO
Tinker's construct
PlusTiC

Crashlog
client:
https://gist.github.com/Staegrin/ad5bd949a6f872a0d962798fa398d01e
latest:
https://gist.github.com/Staegrin/edeb7cc5d6391f72985b3c385aa7c046

**Comment by Landmaster** [comment]
This is the second duplicate of #168 I have gotten so far. **Read [CONTRIBUTING.md](../blob/1.12/CONTRIBUTING.md) *before* you post!**
