### ISSUE TITLE
Unable to craft bolt cores

### ISSUE THREAD

**Issue by Lurmey** [Landmaster/PlusTiC#176]
Hiya, just installed this on my modpack. Upgraded my bronze tools to invar but now I want to do the same with my crossbow bolts but I'm unable to pour neither invar nor lumium onto either a wooden or treated wood arrow shaft or tool rod. I've tried all combinations of these and checked the configs, nothing gives. Any idea what's wrong?

**Comment by Landmaster** [comment]
Do you have a screenshot?

**Comment by Lurmey** [comment]
Is a screenshot necessary? I simply can't pour Invar or Lumium onto an arrow shaft placed on a casting table. I click the faucet and the metals just don't want to pour. I'm an experienced Tinker, I've checked that I'm not making a rookie error like forgetting to put the metal to the bottom of the smeltery.

**Comment by Landmaster** [comment]
Try reproducing with only Mantle, Tinkers Construct, PlusTiC, and Thermal Foundation.

**Comment by Lurmey** [comment]
Reproduced, same results. Screenshots: https://imgur.com/a/MpGnC
