### ISSUE TITLE
Option to disable "Glowing" trait

### ISSUE THREAD

**Issue by Lurmey** [Landmaster/PlusTiC#177]
I have a lumium crossbow and while having it place down glowballs in caves is helpful, I don't want it placing them outside at night. I read that there's a GUI to disable certain traits on tools but it doesn't seem to work with Glowing. Can this be a thing, please?

**Comment by Landmaster** [comment]
The Glowing modifier is *not* added by PlusTiC (it's a native modifier of standard Tinkers Construct); thus, I can do nothing about this. (The Toggle API is added by PlusTiC, and requires coding into the modifier.)
