### ISSUE TITLE
Fluid as Item?

### ISSUE THREAD

**Issue by Arkimu** [Landmaster/PlusTiC#178]
I was trying to add Alloys with Craftweaker, but can't seem to find a way for the alloy recipe to recognice the liquids. 

After cheking some stuff I saw that the liquids/fluids loaded by PlusTiC are not categorise as Fluids but as Items and as is not a ILiquidStack the script dosen't work.

Just wanted to know if that is a bug or is intended (or maybe i'm wrong), because if so is a shame, it would be great to add custom alloys using the stuff added by PlusTiC .

**Comment by Landmaster** [comment]
It appears that you are looking at the wrong section of JEI. Make sure you are getting the *fluid name*, not the block name.
