### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Landmaster** [Landmaster/PlusTiC#18]
If anyone has localizations for other languages, feel free to make a pull request.

**Comment by SirWindfield** [comment]
I will provide a  german translation then :smile:
Quite off-topic though:
I wanted to get started with Minecraft Modding. Are there any good tutorials you could recommend? My first "project" would be a workable version of "Another one bites the dust" for 1.10.2. Looks like no one has ported it to 1.10.2. Coding against CompatLayer should make it work under 1.11 too I guess.

**Comment by Landmaster** [comment]
@SirWindfield Here are a few good tutorials:
- [Shadowfacts](https://shadowfacts.net/tutorials/)
- [McJty](http://wiki.mcjty.eu/modding/index.php/Main_Page)

**Comment by SirWindfield** [comment]
ty :smile:

**Comment by Landmaster** [comment]
zh_CN l10n added (thanks @DYColdWind)
