### ISSUE TITLE
[Suggestion] Constructs Armory Support

### ISSUE THREAD

**Issue by KIdWither** [Landmaster/PlusTiC#184]
Constructs armory adds in tcon armors, would be cool to see some materials added in by this mod to be there. 
Link to mods GitHub: https://github.com/TheIllusiveC4/ConstructsArmory/issues?q=is%3Aopen+is%3Aissue

**Comment by YaibaToKen** [comment]
Duplicate of #175 and #181

**Comment by Landmaster** [comment]
Now that the mod has stabilized to beta (it appears), I will look into support for it.
