### ISSUE TITLE
Tools with Chunky don't drop experience chunks

### ISSUE THREAD

**Issue by randomlypickedname** [Landmaster/PlusTiC#195]
A couple players on our server have noticed that tools with the Chunky trait don't seem to produce experience chunks like the soulium dagger does, though all other mob chunks seem to be fine. Tested with a broadsword, yoyo, and laser gun so far, though I can test more if necessary.

PlusTiC ver. 6.5.1.0
Mystical Agriculture ver. 1.6.10

**Comment by Landmaster** [comment]
The Chunky trait is not added by PlusTiC.
