### ISSUE TITLE
Crash with PlusTiC and ArmouryExpansion and OpenTerrainGenerator

### ISSUE THREAD

**Issue by Khaeops** [Landmaster/PlusTiC#208]
This is a bit of an oddball.
PlusTiC and ArmouryExpansion are seemingly incompatible with each other, as playing the game with only one of them works, but not both. With both enabled, the game results in a crash after loading a world and a specific chunk.

VanillaFix intercepted the crash and states that the cause is OpenTerrainGenerator, but that doesn't seem right. The crashlog is attached, and the error seems to have something to do with biomes. But OpenTerrainGenerator is supposed to ignore biomes and generate terrain using vanilla elements.

[crash-2018-06-27_15.46.08-server.txt](https://github.com/Landmaster/PlusTiC/files/2238654/crash-2018-06-27_15.46.08-server.txt)

**Comment by Landmaster** [comment]
According to the crash log, this has nothing to do with PlusTiC.
