### ISSUE TITLE
[Feature Request] More fine-grained config for materials

### ISSUE THREAD

**Issue by Saereth** [Landmaster/PlusTiC#21]
A more specific config option for materials would be great if possible. For instance, most of the botania integration is fine, but giving people 10 modifiers on a fresh hammer via living for example takes the mod changes outside of what we're looking for in our pack.  Being able to disable living wood or alter the amount of modifiers it gives would be great.

Living wood is very easy to make, its already as good as paper x2 and gives ecological on top of it. Honestly if it was just writable and ecological it'd already be very good/highly desired.

**Comment by Landmaster** [comment]
I might look into a config for the amount of modifiers that Livingwood gives.

**Comment by Landmaster** [comment]
This will be added in the next release.
