### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TacticalUniverse** [Landmaster/PlusTiC#216]
Did some testing and this mod is crashing on any new version of forge for 1.12.2 with tinkers

https://gist.github.com/TacticalUniverse/bfd2d174f8c19c799635836bff2e48db

https://gist.github.com/TacticalUniverse/47d27fb236b16c087b7c24a3c93b60f9

https://github.com/SlimeKnights/TinkersConstruct/issues/3631

**Comment by Landmaster** [comment]
The 1st 2 links are dead, so closing due to lack of information.
