### ISSUE TITLE
Request - Simple Ores 2 Ingot Support 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Landmaster/PlusTiC#224]
![2018-10-31 04_32_55-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/47779048-37a51080-dcc6-11e8-89a0-a3d4f4b734ad.jpg)
![2018-10-31 04_33_03-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/47779049-37a51080-dcc6-11e8-887c-3417a08312ac.jpg)
![2018-10-31 04_33_11-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/47779050-37a51080-dcc6-11e8-879e-41de279983ec.jpg)
![2018-10-31 04_33_18-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/47779051-383da700-dcc6-11e8-86ac-75b1fce7569e.jpg)
![2018-10-31 04_33_27-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/47779052-383da700-dcc6-11e8-989e-e474e9617ea3.jpg)

Simple Tcon Is greatly out of date.

**Comment by sTiKyt** [comment]
@P3rf3ctXZer0 mod "SimplOres 2" have OreDictionary entries?

**Comment by P3rf3ctXZer0** [comment]
I believe so you would have to ask @Sinhika

**Comment by Landmaster** [comment]
Closing because SimpleTCon exists for 1.12.2.
