### ISSUE TITLE
[6.5.3.0] Issue with Lucraft core mod

### ISSUE THREAD

**Issue by KayZiomalek** [Landmaster/PlusTiC#225]
When i have Lucraft and PlusTiC together then PlusTiC like disables (even tho in config it is enabled) Osmiridium and probably more mixed metals that need other mods like Mekanism and Thermal Expansion for example. And this probably happens since Lucraft has Osmium and Iridium too.
It also disables Pyrotheum as fuel.

I hope it will get fixed but to be fair Lucraft bring bunch of bugs to other mods (that are stable).

**Comment by Landmaster** [comment]
> I hope it will get fixed but to be fair Lucraft bring bunch of bugs to other mods (that are stable).

File a report on their end.
