### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DemonfangArun** [Landmaster/PlusTiC#227]
Forge 2768
plustic 6.5.4.0

Crash on startup, only happens on dedicated server

[crash-2018-11-08_12.11.22-server.txt](https://github.com/Landmaster/PlusTiC/files/2562994/crash-2018-11-08_12.11.22-server.txt)

**Comment by Deadmann1** [comment]
Dito

**Comment by Shoulon** [comment]
I can also confirm this

**Comment by LemADEC** [comment]
This is a regression introduced in 6.5.4.0. Consider downgrading to version 6.5.3.0 until a fix is available.

**Comment by TheSnowyChickens** [comment]
Hi, is this maybe the same crash ?
[crash-2018-11-20_05.04.33-server.txt](https://github.com/Landmaster/PlusTiC/files/2600146/crash-2018-11-20_05.04.33-server.txt)
