### ISSUE TITLE
[Feature Request] Disable automatic alloying.

### ISSUE THREAD

**Issue by Lgk2** [Landmaster/PlusTiC#23]
PlusTiC automatically adds alloying recipes for tinkers' smeltery when i make custom ender io alloy-smelter recipes. The problem is that my custom recipes are supposed to be more expensive energy wise (and they take more time to make). So right now i have to make a tinkers' minetweaker script file and remove the added alloying recipes. Would it be possible to add a config option for this behavior?

**Comment by Landmaster** [comment]
added in d45dfa562303dfa43e803a74bc49d36b151755ff
