### ISSUE TITLE
[Not important] Russian Translator

### ISSUE THREAD

**Issue by sTiKyt** [Landmaster/PlusTiC#245]
I really wanna help, i can make Russian and Ukrainian translations but i'm very beginner and don't know how to start(How to setup Java Dev environment for minecraft modding & how to load mod files into it)

**Comment by Landmaster** [comment]
- https://mcforge.readthedocs.io/en/latest/
- For translations, the files go in [this folder](https://github.com/Landmaster/PlusTiC/tree/1.12/src/main/resources/assets/plustic/lang) with the name `language_code.lang` where `language_code` is the desired [locale code](https://minecraft.gamepedia.com/Language) for your language.

**Comment by sTiKyt** [comment]
@Landmaster how can i fix that?
![selection_058](https://user-images.githubusercontent.com/35602029/51097401-67938880-17cc-11e9-9b42-285625bf7dbc.png)
