### ISSUE TITLE
Traits configuration

### ISSUE THREAD

**Issue by LemADEC** [Landmaster/PlusTiC#247]
Please provide a way to configure traits, for example disabling all or some effects of the Illuminati one.

**Comment by Landmaster** [comment]
See https://github.com/jaredlll08/ModTweaker/issues/567

**Comment by LemADEC** [comment]
Effects caused by the traits can be changed in the handler, for example here: https://github.com/Landmaster/PlusTiC/blob/de3e2ed64f632c042a2548648bca6f13f6a834e7/src/main/java/landmaster/plustic/traits/Illuminati.java#L23

Traits can be disabled by changing the logic during registration, for example here: https://github.com/Landmaster/PlusTiC/blob/4d3e91a947b685db847515b5ed669ab66cfb8c5f/src/main/java/landmaster/plustic/modules/ModuleMekanism.java#L72
