### ISSUE TITLE
Compatiblity with MoarTinkers

### ISSUE THREAD

**Issue by vrork** [Landmaster/PlusTiC#25]
https://gist.github.com/vrork/d1b940edc9d17c8ee738c5d1fab808aa

**Comment by Landmaster** [comment]
> As long as we get the config file, we get compatibility i think, because we can enable/disable on your mod things that are also on the other mod

You mentioned the fix for this issue in your own comment in Bartz24/MoarTinkers#3. It's up to @Bartz24 to add the configs for his own mod, because I have configs already; but see #21.

**Comment by Landmaster** [comment]
Since @Bartz24 has yet to publish any mod config on GitHub (and PlusTiC has new TiC weapons, allowing both this mod and Moar Tinkers to be used for distinct purposes [i.e. not just to add new materials]), I will close this issue on my side, and leave discussion of this issue to Bartz24/MoarTinkers#3.

**Comment by Landmaster** [comment]
@vrork  **Update Moar Tinkers. @Bartz24 has now released configs for materials at long last.**

**Comment by vrork** [comment]
I saw it. i now have to see wich i have to disable

**Comment by Dimentive** [comment]
Has compatibility with [Moar Tinkers](https://minecraft.curseforge.com/projects/moar-tinkers) been added yet, or can they still not be used together?

**Comment by Landmaster** [comment]
The configs need to be tweaked by the player.

**Comment by Dimentive** [comment]
Hmm, okay. I haven’t played _too_ much with Moar Tinkers, so I don’t really know what I need to change or add.

Is there an example config anywhere that’s compatible with the latest versions of both mods?

**Comment by YaibaToKen** [comment]
@Landmaster both you and @Bartz24 just need to check if a material already exists before trying to register it. If you try to add onto what exists or not after that is up to you, but it should lessen the amount of complaints and is a fairly trivial change.

**Comment by Landmaster** [comment]
@YaibaToKen It is not, due to the load order of the mods as well as their configs being highly difficult to control.

**Comment by YaibaToKen** [comment]
Both mods should always provide a config to disable their materials, but the mentioned system will stop it from needlessly crashing. Mind you, TiC should do that itself, but it doesn't.
