### ISSUE TITLE
Pyrotheum isn't used

### ISSUE THREAD

**Issue by LemADEC** [Landmaster/PlusTiC#251]
As already reported, still valid in 7.0.1.0, the mod doesn't use Pyrotheum temperatures to smelt redstone into Destabilized redstone
![image](https://user-images.githubusercontent.com/4776032/51940890-807a7b80-2413-11e9-97b4-c7f25c3293c9.png)
![image](https://user-images.githubusercontent.com/4776032/51940919-90925b00-2413-11e9-94d8-af1fbca6e9fe.png)
![image](https://user-images.githubusercontent.com/4776032/51940929-98ea9600-2413-11e9-8f73-b77ac4958a16.png)

Same goes with the other fluids from ThermalFoundation:
![image](https://user-images.githubusercontent.com/4776032/51940984-b455a100-2413-11e9-8248-c095e964d169.png)
![image](https://user-images.githubusercontent.com/4776032/51940992-b9b2eb80-2413-11e9-871b-42bb71241586.png)

**Comment by Landmaster** [comment]
This is not an issue. Both Pyrotheum and Lava are intended to work to melt the Thermal Foundation materials.
