### ISSUE TITLE
Game Crash when adding PlusTic

### ISSUE THREAD

**Issue by daFritzi** [Landmaster/PlusTiC#254]
Adding PlusTic to my Modpack and loading a world created prior to adding the mod causes the game to crash. In that world I have already created tinkers construct structures. I play survival, not creative if that makes a difference.

Creating a new world seems to work though.
I tried removing all the tinkers construct blocks/items from the old world, but that didn't work either (I might have missed one somewhere though...).

This happens with both the stable release as well as with the latest beta release.
The same issue happens when adding the Mod "Moar Tinkers", which is quite similar to this mod.

Crash Log is attached.
Hope this helps you.

[crash-2019-02-01_19.26.26-server.txt](https://github.com/Landmaster/PlusTiC/files/2823688/crash-2019-02-01_19.26.26-server.txt)

**Comment by Landmaster** [comment]
This is definitely not a PlusTiC issue; it looks like the issue is coming from Aether, which, if I recall correctly, is not supported by Tinker's Construct.
