### ISSUE TITLE
Crash in the nether

### ISSUE THREAD

**Issue by GeekJokes** [Landmaster/PlusTiC#255]
I crashed in the nether after a ghast fired at me, and i suspect it triggered a tiberium ore vein ;_;
I'm using VanillaFix, so it took me to the title screen instead of closing the game. The world crashed again upon reload.
VanillaFix' links for both crashes: 
https://paste.dimdev.org/dosiwatozo.mccrash

https://paste.dimdev.org/omacegacek.mccrash

And the normal crash-logs:
[crash-2019-02-04_18.49.06-server.txt](https://github.com/Landmaster/PlusTiC/files/2830023/crash-2019-02-04_18.49.06-server.txt)

[crash-2019-02-04_20.04.38-server.txt](https://github.com/Landmaster/PlusTiC/files/2830024/crash-2019-02-04_20.04.38-server.txt)

**Comment by Landmaster** [comment]
Update to PlusTiC 7.0.2.1.
