### ISSUE TITLE
Weird bug in server log

### ISSUE THREAD

**Issue by Modpack-Support** [Landmaster/PlusTiC#260]
https://gist.github.com/Modpack-Support/357504647ea70e42be7ef13efd2025dc

**Comment by Landmaster** [comment]
This is normal. FML aggressively tries to inject capabilities regardless of whether the class is present on the server, and if it fails, it simply logs a warning without ill effect.

**Comment by illuminati11** [comment]
Unfortunately, the link to the log was removed from there, but i think i have the same issue: https://pastebin.com/aq1yjCmj
If so, is it possible to prevent such errors from being logged? Maybe checking whether the mod is present manually? Or just try-catch to suppress (not really a good way for fixing it).
