### ISSUE TITLE
[suggestion] Lasergun is op if you can shoot through walls.

### ISSUE THREAD

**Issue by Freebi85** [Landmaster/PlusTiC#261]
Hello =)

I know it's wanted that the laser gun can shoot through walls. But is there perhaps a way to add a config to turn it off? Especially in combination with lumium it is super op. That would be very nice :-)
Freebi

**Comment by Landmaster** [comment]
Shooting through walls is intended behavior.

**Comment by mrdeadlocked** [comment]
This would be great to have as a config option. Laser Penetration on/off.
