### ISSUE TITLE
[Feature Request] Tinkers Paxel

### ISSUE THREAD

**Issue by APTJackRichardson** [Landmaster/PlusTiC#264]
How about adding a Pickaxe/Axe/Shovel all in one tool, which requires the tool forge to make. No special effect, just an upgraded Mattock that trades Hoe functionality for being also registered as a Pickaxe. 

Tool parts: Pickaxe head, Axe head, Shovel head and Tool rod, could also include a tool binding but 4 parts seems standard. 

Would allow a knightslime tool head to really shine, reduce inventory bloat and provide a nice 'around the base' tool for quick repairs or modifications.
 
With height & width modifiers would allow easy creation of tunnels without being slowed down by dirt/gravel pockets, and makes exploring mineshafts less fiddly.

**Comment by Landmaster** [comment]
No. That consolidates too much in a Tinkers tool.
