### ISSUE TITLE
Emerald bolt core

### ISSUE THREAD

**Issue by WarrenElite** [Landmaster/PlusTiC#269]
I tried pouring emerald over a wither bone core and nothing I did could make it work, emerald doesn't seem to work on any other cores either although I have only tested wood. I am playing on the project ozone 3 modpack but I don't believe it is a config setting.

**Comment by Landmaster** [comment]
Done in 7.1.6.0

**Comment by thakyZ** [comment]
I have just tested if this was still possible in 7.1.6.1 and it appears not able to be done. I am playing on Enigmatic 2
