### ISSUE TITLE
endspeed not working on shuriken

### ISSUE THREAD

**Issue by dan3401** [Landmaster/PlusTiC#271]
When a shuriken has the end speed modifier (either by embossing enderium or making the item out of it) the shuriken does not teleport
**how to recreate:**
make a shuriken out of enderium and use it
**mod version:**
7.0.5.0
**tinkers version:**
1.12.2-2.12.0.115

**Comment by Landmaster** [comment]
Unfortunately, I cannot do anything about this because Endspeed is a vanilla Tinkers trait, not a PlusTiC trait.
