### ISSUE TITLE
[Question] Do Construct’s Armory traits stack between different armour pieces?

### ISSUE THREAD

**Issue by Dimentive** [Landmaster/PlusTiC#272]
For instance, if my helmet, chestplace, leggings, and boots all have a trim made of emerald, does the Terrafirma effect, which heals me when wearing the armour, quadruple or stay the same?
I.e., if I care about the traits, should I not use the same material for any of my armour?

[On Reddit](https://www.reddit.com/r/feedthebeast/comments/b2o4wg/do_constructs_armory_traits_stack_between/eiu5thw/), the developer of Construct’s Armory told me that traits do stack, but since Terrafirma is a trait added by PlusTiC, they did not know if this particular trait stacks.

Do PlusTiC traits stack if you have the same trait on multiple different pieces of armour?

**Comment by Landmaster** [comment]
Terrafirma, specifically, *should*.

**Comment by Dimentive** [comment]
All right, thanks.

What other PlusTiC effects stack between armour pieces?

**Comment by Dimentive** [comment]
Also, I have another question: Can you stack Botanical (gives you more modifier slots) with Botanical—or only with Botanical II?

And how many modifier slots does each level of Botanical give you?

I love the mod, by the way! PlusTiC is so much fun!

**Comment by Landmaster** [comment]
Botanical I should only stack with II. The first level gives 1 extra, the second 2, if I am correct.

**Comment by Landmaster** [comment]
Also, Terrafirma should be the only armor trait that stacks so far.

**Comment by Dimentive** [comment]
All right. Thank you for clearing it up!
