### ISSUE TITLE
[suggestion] Laser gun needs more serious balancing

### ISSUE THREAD

**Issue by Kazzamkablam** [Landmaster/PlusTiC#275]
I feel current iteration of laser gun is massively overpowered compared to what you need to make one, it should be more in line with other tinker's tools. 

In it's current form there is little need to use anything else once you get one, including melee weapons, as simply spamming laser gun and pretty much anything just instantly dies without ever being threat to you.

It needs to have real downside to using, maybe charge up time or make it cost much more energy.

My 2 cents.

**Comment by Landmaster** [comment]
That may be something I will consider for 1.13 and later. Perhaps a config may be added in the meantime. But not now.
