### ISSUE TITLE
Jetpack Pancakes Hippos not Working! (Simply Jetpacks 2 MC 1.12.2)

### ISSUE THREAD

**Issue by FriendlyGamer** [Landmaster/PlusTiC#276]
Literally this won't work even though that mod's jetpacks are. Tested this with the iron jetpack and I cannot get/know the RF content of these. I am just using the Vanilla integration as I use Mekanism as my tech base instead of the two other popular mods.  

The only thing that does "works" is that the jetpack will be installed onto the chestplate and the hover/engine will toggle but you literally cannot use this modifier.

**Comment by Landmaster** [comment]
Use a separate battery to power the jetpack; PlusTiC's jetpack modifier will drain it from the inventory. Do note, however, that Baubles does not work yet.
