### ISSUE TITLE
Missing Materials: ProjectE's Red Matter, Dark Matter

### ISSUE THREAD

**Issue by markismodded** [Landmaster/PlusTiC#293]
Despite the inclusion of ProjectE on my modpack, the exclusion of it's materials is odd.
![image](https://user-images.githubusercontent.com/39780196/59124539-98b05900-8925-11e9-8eec-999be9df79b2.png)
![image](https://user-images.githubusercontent.com/39780196/59124598-be3d6280-8925-11e9-8773-f196fc895cb3.png)
(the reason for the 7.0.6.1 version is due to my attempt to "Rollback" a version to see if the problem persisted. the attempt resulted in failure)
Interestingly, it seams as though the materials still somewhat exist, as a pickaxe i made with such materials persisted despite the missing materials to construct it, (Which has, sadly, been lost to the void during a fight with the Ender Dragon) It still had the same effects, and stats as the old materials.
Please advise.

**Comment by PitchBlackLaser** [comment]
So how is the issue going along? also I don`t get what you are saying exactly (my english is not that good)
does rolling it back bring the materials back? and if so which version of the mod does still work?

I had Moar Tinkers before this mod and I was happy that this has more support for the mods I use but if the (to me at least) most important one is missing it would be bad :/ (so for help Moar Tinkers ProjectE integration still works...maybe take a look at that)

**Comment by Keb911** [comment]
I'm getting this in a mod pack, by the looks of things it's not plustic doing it. Ran projecte 1.12.2 PE1.4.1 and plustic 7.0.7.0 by themselves without any issues.

**Comment by kohlth** [comment]
if you have this issue just delete the armory expansion config and when you load up mc everything should work fine

**Comment by Landmaster** [comment]
Yeah I don't support Armory Expansion.
