### ISSUE TITLE
livingwood material missing?

### ISSUE THREAD

**Issue by zeantra** [Landmaster/PlusTiC#295]
as of 7.0.7.0 the living wood material seems to be missing. i do play with alot of other mods, but in 7.0.5.0 there was no issue, and my mods haven't changed since....

**Comment by mjtaft4** [comment]
I've been having this issue myself in 7.1.0.0 as well. For me it's the entirety of Botania's materials. I've found that they will appear as expected when configs are initially generated, I can make tools with them. But if at any point after that I close the game and reopen it the parts are gone. They have no stats on my created tools, modifiers still seem to work, and so far only deleting configs seems to help. I'm currently trying to nail down what config specifically I have to delete. Up until this point I've just been deleting my entire config folder.

**Comment by dralom** [comment]
I have the same problem with FTB Revelations 2.7.0, running Java 8 211.
Plustic 7.0.7.0 
TConstruct-1.12.2-2.12.0.113 or TConstruct-1.12.2-2.12.0.157
Botania r1.10-358 or Botania+r1.10-361

**Comment by Landmaster** [comment]
Closing as an Armory Expansion issue, as it is not supported.
