### ISSUE TITLE
New weapon: Laser gun

### ISSUE THREAD

**Issue by Landmaster** [Landmaster/PlusTiC#30]
Feel free to leave any suggestions about this new weapon here.

**Comment by Jacky1356400** [comment]
Laser gun... sounds interesting to be a Tinkers' weapon.
Unlike bow or crossbow, I think laser gun should take both RF and durability to operate.
Also, the projectiles should be able to travel for a quick, far distance, not affected by gravity and have the ability to set opponents on fire.

**Comment by vrork** [comment]
I dont think Laser guns fit the style of tinkers. I would suggest blow pipes instead.

**Comment by Landmaster** [comment]
The laser gun is added in a beta release (4.5.0.0).
