### ISSUE TITLE
Brown magic not teleporting

### ISSUE THREAD

**Issue by 252rer** [Landmaster/PlusTiC#301]
I'm having trouble getting the brown magic teleport to work even after assigning keys for both it and the set portal. Hitting one buttons do nothing on their own but holding shift and the set portal button says "set teleportation point for armor to be (actual cords) in dim 0". All of my construct's armory set has 1 piece made of osgloglas.

**Comment by Landmaster** [comment]
- The set portal is working properly.
- Make sure you have updated to latest mod versions, and no keybinds is conflicting with the others. In my experience, some combinations do not work well with Minecraft.
