### ISSUE TITLE
Material Traits and Tweakers Construct

### ISSUE THREAD

**Issue by deepfoundLava** [Landmaster/PlusTiC#303]
Is there a list for the Ids of all traits Plustic adds for use with Tweakers Construct? For example, if I want to add "Hail Hydra" trait to wood, what should I refer the trait as?

**Comment by Landmaster** [comment]
They're inside the class files in https://github.com/Landmaster/PlusTiC/tree/1.12/src/main/java/landmaster/plustic/traits (albeit *not* the names of the files themselves)

**Comment by JohnTitor95** [comment]
could you be a little more explicit where exactly the names are? Many of the traits ive tried simply don't work, despite using the names in that exact directory. Is it the string inside super()? Or is it the public static final ____? Or is it the public static final _____ variableName? Or something else entirely?
I can't get Haoran's cult to apply despite having tried haorans_cult, haoranscult, and HaoransCult.
Same goes for terrafirma.
