### ISSUE TITLE
Incompatibility with Thermal

### ISSUE THREAD

**Issue by Saphirrcr** [Landmaster/PlusTiC#306]
By adding PlusTIC in a modpack, it get possible to place the molten resources from Thermal Foundation (exept Constantan which can't be placed at all). But there are no textures when placed.

Screens : 
[https://cdn.discordapp.com/attachments/495651683808968706/607283717949358080/2019-08-03_20.48.18.png](url)
[https://cdn.discordapp.com/attachments/495651683808968706/607284147852935178/k.png](url)

**Versions :**
Minecraft - 1.12.2
Forge - 2825
//
CodeChickenLib - 3.2.2.353
JustEnoughItems - 4.15.0.268
NotEnoughItems - 2.4.2.240
//
CoFHCore - 4.6.3.27
CoFHWorld - 1.3.1.7
RedstoneFlux - 2.1.0.6
ThermalDynamics - 2.5.5.21
ThermalExpansion - 5.5.4.43
ThermalFoundation - 2.6.3.27
//
Mantle - 1.3.3.55
TConstruct - 2.12.0.157
//
PlusTIC - Both 7.1.0.0 and 7.0.7.0

**Comment by Landmaster** [comment]
The molten stuff are actually added by Thermal; only the tool stuff is done by PlusTiC. Report this to CoFH.
