### ISSUE TITLE
Option to enable all materials, even if the mods that normally add the material aren't detected

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Landmaster/PlusTiC#307]
For example, this setting would enable Osgloglas even if Mekanism isn't detected. This would enable molten Osgloslas, the tool parts, and the tools.

It doesn't need to be obtainable in survival mode. I can add my own recipes with CraftTweaker scripts.

**Comment by Landmaster** [comment]
Why do you need this?

**Comment by TheDeviantCrafter** [comment]
There are a bunch of fun materials that don't exist in my pack because I don't have a mod that adds those materials. The Mekanism materials and their high base stats come to mind, but there are others.

I'd like to add a few of those to my pack. I'm willing to add custom recipes and even make some custom ingots using ContentTweaker to make it work.

**Comment by Landmaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/infini-tic, combined with PlusTiC's recently added (i.e. just today) config option to force trait loading, is what you're looking for.

**Comment by TheDeviantCrafter** [comment]
Can Infini-TiC use traits of materials that Plus TiC doesn't load?

**Comment by Landmaster** [comment]
As I have said, PlusTiC now has a config option to force-load traits that it otherwise wouldn't.
