### ISSUE TITLE
[Feature Request] Further Substratum support

### ISSUE THREAD

**Issue by Arakhor** [Landmaster/PlusTiC#31]
Hello. Could you please add support for Substratum's invar, lumium and chromium? Or even just invar would be a big help with the modpack I'm working on.

**Comment by Landmaster** [comment]
Invar is already added in the Base module as of 4.3.0.3. Lumium is something I would consider.

**Comment by Arakhor** [comment]
Oops, time to update then, my bad. Thanks.

**Comment by Landmaster** [comment]
Lumium is added in 4.3.2.0.
