### ISSUE TITLE
Missing Materials: Red Matter, Dark Matter and others

### ISSUE THREAD

**Issue by Zecheariah** [Landmaster/PlusTiC#312]
I installed PlusTic and it worked great, I had Red Matter Tools and Dark Matter but then the private Server I have up crashed, so i restarted it and now most of the materials that PlusTic adds is gone. (I just know about Red Matter and Dark Matter because I was making a took out of them) Looking at the "Missing Materials: ProjectE's Red Matter, Dark Matter" I deleted the armory expansion's config and restarted the server and it didn't work so I deleted all tinker's related configs and it worked again. but then the server crashed again (This was over the span of a few days the server doesn't crash every 5 minutes) and the materials are gone yet again. Only for the tools anyway, the armour is still there and working. I've also tried deleting every config and running it again and they're still gone. The odd part is, is that on another computer I downloaded the modpack, went into single player and the tools were working so I copied the entire config folder of the other computer into the server's config and started it up but alas the tools weren't there. So I'm thinking that it's either one of the configs and a server restart enacts the problem or it's the server restarting itself that breaks it? I'd love some guidance with this as Red Matter tools would be great.

Modpack: Borked Craft (on Twitch)
Forge Version: 14.23.5.2838
Minecraft Version 1.12.2

Update: I made a custom profile with the same mods and did some experimenting, it seems like if I mess with any of the configs in the entire modpack it disables the materials. I changed Dungeon Tactics to not spawn ore clusters and they went away. I gave ProjectE custom EMC values and they went away and I made Refined Storage not need power and the materials, again, went away. I even changed what Morpheus said to players when they go to sleep and the same happened. The problem does get fixed when I delete every config and restart the game but I need to change the configs of some mods like ProjectE for the sake of my modpack.

**Comment by Landmaster** [comment]
Armory Expansion is not supported.

**Comment by Zecheariah** [comment]
It’s not the armor that’s not working it’s the tools. The armor works fine
but when i say “the materials” are not working I mean for the tools. Sorry
for the misunderstanding. So the problem with the tools is that I have
armory expansion in the mod pack so PlusTic just deactivates itself?

**Comment by Landmaster** [comment]
Armory Expansion causes problems for entire materials. I suggest you don't use that mod, as I will be adding ConArm support myself.

**Comment by Zecheariah** [comment]
Oh, that explains it so much better, I’ll definitely remove it until
support is added. Thank you so much!
