### ISSUE TITLE
More Advent Of Ascension Content

### ISSUE THREAD

**Issue by Pokesmile-modded** [Landmaster/PlusTiC#316]
Recently PlusTic added Advent Of Ascension materials to the game (Limonite, Rosite) and I was so happy to test them with my modpack but when I got more advanced in my test survival I got stuck in cobalt tools, I mean, there were a lot more of metals and ores that could be added to the game and being better than cobalt. Ok, so my request is to add these materials to PlusTic AoA3, because when you get to new dimensions where mobs are very powerful I couldn´t kill them easily with my manyullyn sword... 
Materials to add:
Molten: Skeletal, Jade, Amethyst, Sapphire, Emberstone, Elecanium, Shyrestone Ingot, Baronyte, Lunar, Varsium...
Craftable: Jewelyte, Ornamyte, Bloodstone, Crystallinite, Gemenyte, Runium Chunk, Shyregem, Ghoststone...
Feather: Opteryx

Before PlusTic aoa3 materials existed I used a script called Advent Of Ascension Tic Bridge (by Partonetrain that added AoA3´s Materials to the game but didn´t add bow stats and the molten materials looked like water

Sorry if I wrote something wrong my english is not as good as would want it to be :).

**Comment by Landmaster** [comment]
I am already in the middle of doing so.

**Comment by Pokesmile-modded** [comment]
Nice :D it will be a great mod in the future
