### ISSUE TITLE
[Feature Request] Gems+ Support

### ISSUE THREAD

**Issue by BrisingrAerowing** [Landmaster/PlusTiC#32]
[Gems+](https://minecraft.curseforge.com/projects/gems) adds a whole bunch of Gemstones that would be nice to have in Tinkers.

Idea for one gem:

Phoenixite - Something fire related (like fire aspect on a sword or flame on a bow, or even an auto-smelt ability)

**Comment by Landmaster** [comment]
@BrisingrAerowing This will probably be the last set of materials that will be added to PlusTiC before I update it to Minecraft 1.12. Gems+ support should be added in 5.2.1.0.

**Comment by Landmaster** [comment]
Added in df48651dd771e253165f60e5d13b31c015ac0849
