### ISSUE TITLE
Suggestion: Better Blind Bandit spawning system.

### ISSUE THREAD

**Issue by SirAron111** [Landmaster/PlusTiC#321]
Suggestion: Better Blind Bandit spawning system.

Make Blind Bandit not spawn directly in the players face as you mostly hit the bandit and this makes it turn against you. Have them spawn on the side or with a little random offset.

Also since Blind Bandit mostly is on the Draconic stuff and I have never seen it on any other material. Can’t you turn it into something more fun like little dragons not these black with wanna be zombies?

Also give it a cap for how many can be active at a time really you can spawn like a hundred of them way to fast to crowd the vision.

**Comment by Landmaster** [comment]
`this makes it turn against you.`

You sure this is the case? I coded the Bandit specifically not to attack the summoner.

**Comment by SirAron111** [comment]
Ye some mods adding ai that makes mobs retaliate etc can cause this but the main part of the annoyance even if they don’t turn against you it’s that they spawn literally in your face making half your sword hits hurt them or simply have your own summoned bandits soak dmg for whatever you plan to attack.

They also block your ranged attacks since they have basically zombie size… that’s why I thought having a more out of the way spawning and a smaller/different model would be a good thing as well as a cap because with a fast weapon you can literally summon hundreds of them.

**Comment by Landmaster** [comment]
Done in 7.1.6.0

**Comment by SirAron111** [comment]
MM strange with the 7.1.6.0 version now it doesn’t spawn them at all. Instead if makes mobs randomly teleport around when I hit them (tested on zombie pigmans and zombies with wyvern parts) and sometimes even freezes when I rapid fire with the laser gun. Didn’t crash just something really strange going on with this now! Also the laser beam appears when I have a mob in target position even if I don’t fire it just stands there not doing dmg until I fire the laser. This also happens when the game starts lagging when shooting/hitting something with a tool like this

**Comment by Landmaster** [comment]
@SirAron111 Fixed in 7.1.6.1

**Comment by SirAron111** [comment]
Now the bandits work great they spawn behind you and a bit o the side so they run past you and don’t get in your way not even when you walk backwards or sideways while fighting. GJ 

(There still should be a cap so that when you rapid fire you can’t spawn hundreds of them XD)

But with the changes made the main problem is solved.

Would love to see some more summon traits on some items like a little fairy on elementiom/terrasteal from botania for example.
