### ISSUE TITLE
[Feature Suggestion / Request] Metallurgy 4 support

### ISSUE THREAD

**Issue by Gebcrafter** [Landmaster/PlusTiC#330]
I used to play silly little modpacks with my friends years ago with Metallurgy 3 and ExtraTiC, it would be so cool to see all the materials from the updated version of metallurgy in the modern minecraft version

**Comment by Davoleo** [comment]
Hey @Gebcrafter I'm the dev of Metallurgy 4: Reforged, we already support TCon's Integration natively, so there's no real need of an additional to do it :P

**Comment by Gebcrafter** [comment]
Oh! That's amazing. Guess I should have checked beforehand, but that's great to hear. Fantastic mod btw, excellent job
