### ISSUE TITLE
[1.10.2] Crash conflict with Moar Tinkers

### ISSUE THREAD

**Issue by MokahTGS** [Landmaster/PlusTiC#34]
https://pastebin.com/puGz1W8N

Getting a crash saying there is a conflict with registered metals.  I realize that these mods do almost the same thing but thought I'd put it here anyway.

**Comment by Landmaster** [comment]
Unfortunately, @Bartz24 has done absolutely nothing ***for over a month*** to add any config on his side (see #25). For now, disable all modules of PlusTiC *except* the Base, Actually Additions, ArmorPlus, and Katana modules.

**Comment by Landmaster** [comment]
@MokahTGS **Update Moar Tinkers. @Bartz24 has now released configs for materials at long last.**
