### ISSUE TITLE
[1.12.2] Attacking mobs with the 'Soul Power' Trait crashes the game.

### ISSUE THREAD

**Issue by Z-Tunic** [Landmaster/PlusTiC#346]
Crash Report:
https://pastebin.com/6TF4aYV4

Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 5
AoA3-3.2.1
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
plustic-7.1.6.1
TConstruct-1.12.2-2.13.0.171

-----

This is perhaps due to an update with Advent of Ascension. Something must've changed with Soul Power as attacking mobs with the Soul Power Trait leads to a game crash.

**Comment by Landmaster** [comment]
AoA support removed in 8.0.0.0
