### ISSUE TITLE
[1.12.2] 'Soul Charge' Trait causes Ghost Blocks to occur.

### ISSUE THREAD

**Issue by Z-Tunic** [Landmaster/PlusTiC#347]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 5
AoA3-3.2.1
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
plustic-7.1.6.1
TConstruct-1.12.2-2.13.0.171

-----

This trait allows you to charge up Soul Power by breaking blocks... however due to an update with Advent of Ascension this trait no longer charges up Soul Power and any blocks broken will become 'Ghost Blocks'.

Ghost Blocks can occur where on the cilent-side it's broken & not there but for the server-side the block is still there.

**Comment by Landmaster** [comment]
AoA support removed in 8.0.0.0
