### ISSUE TITLE
[1.12.2] 'Auto-Repair' Trait is stackable and depending on the tool... can give you more than one modifier if it's unbreakable.

### ISSUE THREAD

**Issue by Z-Tunic** [Landmaster/PlusTiC#348]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 5
AoA3-3.2.1
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
plustic-7.1.6.1
TConstruct-1.12.2-2.13.0.171

-----

Auto-Repair Trait allows you to repair tools as long as you have the correct sharpening kit. If the tool is unbreakable then you are granted 1 modifier, right? Well...

![](https://cdn.discordapp.com/attachments/377171551155650560/668361056342638612/PlusTiCAutoRepairTraitManyModifiers.PNG)
This is with a Shuriken, apparently Auto-Repair Trait can give +3 Modifiers per Knife Piece if I make the tool Unbreakable with 5x Reinforced by Embossing it with a Paper Knife or by adding in a Paper Knife. If you go with embossing... you can gain 12 free modifiers with 4x Rosite Knives. Embossing it with Rosite only grants 1 extra modifier.

If we add all of that up and take away the 5x Reinforced... that's a grand total of 17 Modifiers since each Rosite Knife Blade gives 3 extra modifiers which stacks.

Unbreakable Arrows can get 2 extra modifiers with Auto-Repair but you only have the Arrow Head material to work with. If you emboss Auto-Repair onto any unbreakable tool it only grants 1 modifier regardless of the tool.

**Comment by Landmaster** [comment]
AoA support removed in 8.0.0.0
