### ISSUE TITLE
Brown Magic tool trait desyncs player state when going between dimensions

### ISSUE THREAD

**Issue by NillerMedDild** [Landmaster/PlusTiC#349]
Using any tool with the Brown Magic trait to travel between dimensions desyncs the player state,
this means any hearts you have earned from Spice of Life: Carrot Edition are (visually) removed(this always happens), attempting to sleep in a bed will force you to use /kickme in order to leave the bed(regardless of the sleep charm)(this only happens sometimes), and Actually Additions medium(and I would assume large, but I haven't been able to craft those to test yet) storage crates, the arrow buttons to go to the different pages of storage fail to work(this only happens sometimes), and probably a bunch of other stuff I don't know about.
Swapping dimensions normally removes the desync if it exists.

To reproduce, simply travel to any dimension, and use brown magic to warp to a different dimension, upon warping to the other dimension, all the above things will stop working properly.

### Versions
- Forge-1.12.2-14.23.5.2847
- plustic-7.1.6.1

### Log
https://gist.github.com/NillerMedDild/d20ad790b863d423cd56b0a96861e15b

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1494

**Comment by Landmaster** [comment]
Yeah I need to update the teleportation code, which was based on Mekanism's old stuff back in 1.10.2.

**Comment by Landmaster** [comment]
This will be fixed in 8.0.0.0.
