### ISSUE TITLE
Unable to add lapis to the Katana.

### ISSUE THREAD

**Issue by NillerUdenDild** [Landmaster/PlusTiC#35]
Hey! I posted this on the Tinkers Construct git, where you saw it, but I thought I'd better repost it here.
As the title says, I can't add lapis to the Katana - I assume it's not intended?

Minecraft 1.10.2
Forge 12.18.3.2281
Tconstruct-1.10.2-2.6.3
plustic-4.3.0.3

**Comment by Landmaster** [comment]
Do you have a screenshot?

**Comment by NillerUdenDild** [comment]
![2017-05-01_10 36 14](https://cloud.githubusercontent.com/assets/21295394/25575807/861449f0-2e5a-11e7-9394-65b9377aaaa0.png)
![javaw_2017-05-01_10-35-53](https://cloud.githubusercontent.com/assets/21295394/25575810/87cd9f44-2e5a-11e7-9034-881e1907f05c.png)

Here you go! I also forgot to mention I'm using the Enigmatica modpack: https://minecraft.curseforge.com/projects/enigmatica

**Comment by NillerUdenDild** [comment]
That was fast, thanks a lot!
