### ISSUE TITLE
ParticleEndspeed crashes world when I miss

### ISSUE THREAD

**Issue by kriscrash** [Landmaster/PlusTiC#351]
Make a shuriken with Enderium parts, thus Endspeed modifier.
Be in the Nether(?). Throw at enemy, and miss. 
Host gets kicked out of his world and I disconnect. I assume this is to do with particle age exceeding its intended limit, or the Endspeed ability traveling too far away.
It has happened thrice now, here's two logs
https://paste.dimdev.org/zubiqoyohe.mccrash
https://paste.dimdev.org/banuwucehi.mccrash
My apologies if the core issue is with another mod, I can just see this particle being the crash source.

**Comment by kriscrash** [comment]
I took some time to test this out in singleplayer; creative mode in the nether, pure Enderium shuriken, throw a lot of them around.
have another crash log https://paste.dimdev.org/cibarikuzu.mccrash

1; you don't have to miss, which makes sense because the projectile travels after hitting an enemy.
2; it also works for arrows (probably obvious).
3; it seemed far more stable on my PC than friend's while he hosts, so I threw several before. Dunno if related to chunk drawing distance on client being greater than host.
4; you definitely have to throw the shuriken so it escapes the loaded chunks, and interacts with something on the way, such as an enemy or a lava-fall. That's just unlikely to happen anywhere but the nether I guess, but I'm willing to try.

I know you're phasing out EnderIO support, but if you intend to add a similar modifier to Endspeed (which I hope you do!), maybe make it slightly less than infinitely travelling. Materials that increase travel speed/distance or splash damage/mob piercing seperately would be super.

**Comment by Landmaster** [comment]
Endspeed is a vanilla Tinkers trait. It's not from PlusTiC.
