### ISSUE TITLE
A bug in FlyingRoad 3

### ISSUE THREAD

**Issue by SDC2333** [Landmaster/PlusTiC#357]
At present, my solution is to reenter the game and find myself at the regeneration point after reentering.

**Comment by friendlyhj** [comment]
I'm the author of FlyingRoad 3 modpack. I want to add more info.

Game will crash when using Nick of Time trait in The End.

Crash Report: https://paste.ubuntu.com/p/yy7X9HPp9y/

**Comment by SDC2333** [comment]
Ok,I know that thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "youyihj"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 晚上8:11
收件人: "Landmaster/PlusTiC"<PlusTiC@noreply.github.com&gt;; 
抄送: "&amp;#x1F92A;sdc&amp;#x1F92A;"<3360098364@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Landmaster/PlusTiC] A bug in FlyingRoad 3 (#357)





 
I'm the author of FlyingRoad 3 modpack. I want to add more info.
 
Game will crash when using Nick of Time trait in The End.
 
Crash Report: https://paste.ubuntu.com/p/yy7X9HPp9y/

**Comment by Landmaster** [comment]
- Does this happen with the Nether as well?
- Try reproducing with only PlusTiC and its dependencies.

**Comment by friendlyhj** [comment]
OK, I update Plustic to 8.0.0.0. Game doesn't crash. However, The teleportation point is wrong.
I only install JEI, Tconstuct, Plustic and Thermal Foundation(to get nickel)

https://imgur.com/a/vM1Er6w
