### ISSUE TITLE
<fluid:aluminium> from GTCE is unable to alloy with molten obsidian and iron for alumite 

### ISSUE THREAD

**Issue by ChromaPIE** [Landmaster/PlusTiC#358]
As the title said, the Aluminium Ingot from GTCE will melt into the light-blue color <fluid:aluminium>, but this kind of fluid, maybe because its name is alumin**i**um instead of aluminum, cannot be used in the recipe of alumite. please make a simple compat for aluminium.

**Comment by Landmaster** [comment]
What happens when you use UniDict?

**Comment by ChromaPIE** [comment]
The modpack I am making is based on a GT-style gameplay, so I set up the config of UniDict to make all of the ingots GT, that is where the problem came from, and because Industrial Forgoing is not and won't be included in the pack, so there is no way players can transform the fluids based on the so-called FluidDict, which seems less flexible and configurable than OreDict. Now I have solved the problem by adding a alloying recipe via CrT, but I still hope for a official support if this is not considered unnecessary.

**Comment by Landmaster** [comment]
Not worth it to add official support IMO, since it's a weird edge case that applies to a mod (GTCE) not really designed for interoperability anyway.
