### ISSUE TITLE
Missing?

### ISSUE THREAD

**Issue by DemonfangArun** [Landmaster/PlusTiC#359]
Did you happen to accidentally delete the PlusTiC project from curseforge? I got a message about it being an invalid project today when attempting to upload my pack, and sure enough it's gone. Unfortunately I'm going to have to remove it for the time being.

**Comment by Landmaster** [comment]
I probably accidentally deleted it. I've re-uploaded files at https://www.curseforge.com/minecraft/mc-mods/plus-tic

**Comment by TeetoKaziim** [comment]
There appears only to be a 1.15.2 version of the mod?

**Comment by Landmaster** [comment]
Whoops, I changed it back to 1.12 now!

**Comment by CrankySupertoon** [comment]
@DemonfangArun 
>  accidentally delete the PlusTiC project from curseforge? 

More like legal pressure from curse. Evidence can be seen here https://github.com/Landmaster/PlusTiC/issues/361#issuecomment-615456603

**Comment by DemonfangArun** [comment]
> 
> 
> @DemonfangArun
> 
> > accidentally delete the PlusTiC project from curseforge?
> 
> More like legal pressure from curse. Evidence can be seen here [#361 (comment)](https://github.com/Landmaster/PlusTiC/issues/361#issuecomment-615456603)

Thanks for the link, closing this as well. No need to deal with this crappy dev anymore.
