### ISSUE TITLE
[Feature Request] Add other items from supported mods

### ISSUE THREAD

**Issue by TokkenGmr** [Landmaster/PlusTiC#36]
I was just wondering if there were plans to add any of the [following](https://gist.github.com/TokkenGmr/424f4ca7256177117354b56fd0fe9fb2). Most are from mods that you already added support for some are not. if some of these are added and I somehow overlooked them I do apologize in advance

**Comment by Landmaster** [comment]
As most of these materials have already been added, I'll close this to keep the issue tracker clean.
