### ISSUE TITLE
Please restore all 1.12 versions

### ISSUE THREAD

**Issue by CrankySupertoon** [Landmaster/PlusTiC#361]
Your broke a lot of modpacks including mine

**Comment by Landmaster** [comment]
I probably accidentally deleted it. I've re-uploaded files at https://www.curseforge.com/minecraft/mc-mods/plus-tic

Sorry about that!

**Comment by CrankySupertoon** [comment]
eh excuses. "accidently deleted it". you mean you deleted the entire curseforge page and had to remake it. That doesnt fix the many of modpacks using the old project id

**Comment by DragonmasterDJ** [comment]
Hey hey.. you dont have to say it like that, everyone makes mistakes like this from time to time! It's just going to be hard to find it now, it doesn't come up in my search on the launcher!

**Comment by janagyjr** [comment]
Cranky isn't wrong.

**Comment by basestar237** [comment]
Does anybody know how to fix it?

**Comment by janagyjr** [comment]
Read the thread, Landmaster included a link to the new project page.

**Comment by kreezxil** [comment]
all i'm seeing is 

```
Why is my blue pill turning red?
```

Two very smart people in this thread and their acting like meth addicts.

**Comment by CrankySupertoon** [comment]
> I probably accidentally deleted it. I've re-uploaded files at https://www.curseforge.com/minecraft/mc-mods/plus-tic
> 
> Sorry about that!

You mean Published a Version that automatically kicked StripedRedzone someone you dont like. https://github.com/Landmaster/PlusTiC/commit/9147573c6d514ff88825a8cc1ab8438f9c80a14c#diff-a516bfe6aaa4dd4f38abbd0de3bdd0dbR197

Nice job not knowing what a Force Push is. Imma going to use MoarTinkeres from now on Shame on you

**Comment by CrankySupertoon** [comment]
![image](https://user-images.githubusercontent.com/48419040/79613393-72725280-80cc-11ea-8665-092c9a1ccd34.png)

**Comment by DemonfangArun** [comment]
> 
> 
> Your broke a lot of modpacks including mine

And mine. I'm not sure what happened, but the level of incompetence displayed has forced me to add this dev to my small blacklist. I had to push an emergency update because of this and it didn't make me happy.

**Comment by AzureDoom** [comment]
@DemonfangArun read Crankys comment above https://github.com/Landmaster/PlusTiC/issues/361#issuecomment-615456603 he got butt hurt over a player that was dissing one of their mods so he added the linked code that kicked that player if he used this mod, which in turn made CurseForge delete the Plus TiC project page. Nice ban evasion BTW, removed the reupload as well.

**Comment by kreezxil** [comment]
yep, this is how you get screwed. now the mod has to re-emerge as an
entirely new mod by an entirely new author. One will have to make sure the
uuid kicking code is removed and probably sufficiently change up more than
a few words in it. CF is probably creating filters to search and destroy
this mod since landmaster is repeatedly uploading it under various accounts.

**Comment by aaronhowser1** [comment]
This makes me sad, honestly. The mod dev, in a fit of what can only be described as baby rage, added some code that broke CurseForge's terms of service, and got himself and his mods permabanned. I agree with their decision, mods can't do what this did. What makes me sad is that this small, very stupid decision has completely destroyed the dev's modding career and reputation. I hoped we were passed this as a community.

**Comment by AzureDoom** [comment]
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad for anyone using the 1.12.2 version, someone has taken it over on CurseForge.

**Comment by Pabsb** [comment]
Love how these retards think the code is malicious. If the mod author doesn't want someone to use their mod which is open source they have every right to deny it.

**Comment by AzureDoom** [comment]
> Love how these retards think the code is malicious. If the mod author doesn't want someone to use their mod which is open source they have every right to deny it.

Guess what? By CurseForge rules, it is malicious. They have every right to tell mod authors that do this shit to fuck right off. Landmaster has no right to ban a user from servers they do not own, having the mod on a server grants Landmaster NO power to control who can and can not play it.

**Comment by kreezxil** [comment]
@Pabsb so what you're saying is that if your computer gets infected by ransomware, the owner of the ransomware has every right to charge you whatever they see fit to release your computer back to you?

And yes, this is the same exact concept.

**Comment by kreezxil** [comment]
@Pabsb also you're the retard in this scenario.

**Comment by kreezxil** [comment]
@Pabsb oh shizznat, in this day age of being mindful and respectful how dare you call someone a retard.

**Comment by reasonablm** [comment]
> @Pabsb so what you're saying is that if your computer gets infected by ransomware, the owner of the ransomware has every right to charge you whatever they see fit to release your computer back to you?
> 
> And yes, this is the same exact concept.

No, it is a bad comparison. You can simple decide not to use the mod anymore. Nobody can hold your hostage for that. In the case of ransomware, you don't have a choice but to pay up.

**Comment by reasonablm** [comment]
> > Love how these retards think the code is malicious. If the mod author doesn't want someone to use their mod which is open source they have every right to deny it.
> 
> Guess what? By CurseForge rules, it is malicious. They have every right to tell mod authors that do this shit to fuck right off. Landmaster has no right to ban a user from servers they do not own, having the mod on a server grants Landmaster NO power to control who can and can not play it.

Technically speaking, he is not banning that user from the servers.  He is banning that user from using his mod. Yes, he violated the rule and it's up to Curse to decide the punishment but don't exaggerate this into banning someone from using Curse completely.

**Comment by reasonablm** [comment]
Wow, there were a lot of haters on here because of the inconveniences caused by the ban. Instead of taking a more constructive approach and helped Landmaster get over his mistakes in life, they acted like some self-righteous people but deep down they are just being selfish. When things were going smoothly, they didn't bother to come in here and thank the author for providing this mod to them for free. But when things turn bad, they are quick to come in here with their rages and fire away like Landmaster owed them something.  
At least, someone like  aaronhowser1 expressed some sadness and not just pure rage. I'm sure that this is one lesson that Landmaster will learn from.  Don't lecture others on being mature when you can't be one yourself.  It just showed that you are a hypocrite.

**Comment by kreezxil** [comment]
So what you're saying is that if I provide you meth or smack for free and
later get caught by the police that you're going to stand up in my defense?
Yes it's the same thing.
