### ISSUE TITLE
Illuminati trait

### ISSUE THREAD

**Issue by PossessedDevil** [Landmaster/PlusTiC#365]
So I've been playing with the **Illuminati** trait on my Katana and after I installed _Optifine_, the mobs instead of the weird glow are now completely white. 

Is _optifine_ straight up incompatible or is it something in the settings I need to change?

I tried combing through the issues but didn't find anything on it.

Additional information I'm playing the **ATM3** modpack.
![image](https://user-images.githubusercontent.com/64764953/81116759-35102080-8f26-11ea-9eff-6d68aaebfd92.png)

![image](https://user-images.githubusercontent.com/64764953/81116804-4bb67780-8f26-11ea-8f0f-f934b7eac6ee.png)

**Comment by TeamDman** [comment]
The trait just applies the GLOWING potion effect, which I believe is a vanilla feature.

Very high chance that PlusTiC is unrelated, if you remove it from the pack you'd likely be able to reproduce.
Probably an unlucky Optifine configuration

**Comment by PossessedDevil** [comment]
![image](https://user-images.githubusercontent.com/64764953/81146580-de800200-8f78-11ea-8d30-4072b788e819.png)

Confirmed it was the "Fast Render" option in Optifine settings. Still thanks for response.

Here's a link to optifine where I found out the solution if anyone ever wanders here with the same error.

[https://github.com/sp614x/optifine/issues/1174](url)
