### ISSUE TITLE
[Suggestion] Carbon Nerf and better texture

### ISSUE THREAD

**Issue by vrork** [Landmaster/PlusTiC#40]
Is it possible to make the texure for carbon parts/tools better instead of looking like there is texture missing? Also, nerf carbon heavily. Is easy to get and extremelly OP. I would suggest a little better than iron (on a large blade, around 7 damage at max). The durability is okay, carbon is very durable irl.

**Comment by Landmaster** [comment]
Carbon is **not** added in PlusTiC.
