### ISSUE TITLE
No molten osmium or osmium parts.

### ISSUE THREAD

**Issue by steven-archer** [Landmaster/PlusTiC#47]
Plustic 5.0.1.0 + Mekanism 9.3.1.305 + Forge 2312 (1.11.2)

Can not melt osmium ore in smeltery, and no osmium parts are craftable. Not a single osmium tinkers tool or weapon part shows up in the creative search tab or in JEI. 

Made sure Mekanism integration was enabled and everything else was turned off in the config.

**Comment by Landmaster** [comment]
This has been fixed in development and will be fixed in the next release.

**Comment by steven-archer** [comment]
I found that materials are also missing from some other mods. Specifically Biomes O'plenty, Natura, and Psi. Will those fixes be in the next release also?

**Comment by Landmaster** [comment]
Those will been fixed also.
