### ISSUE TITLE
Crash with newest Draconic Evolution (1.10.2)

### ISSUE THREAD

**Issue by DeadSix27** [Landmaster/PlusTiC#49]
DE: `Draconic-Evolution-1.10.2-2.1.0.232-universal.jar`
PT: `plustic-5.0.1.1.jar`

`Caused by: java.lang.NoSuchFieldError: wyvernCore`

Stacktrace: https://gist.github.com/DeadSix27/72b3933ac75e9fa2578eed2b9127f36a

**Comment by blockbreaker1361** [comment]
I'm getting the same thing. 
https://pastebin.com/CKB69VCJ

**Comment by Protheus** [comment]
Disable Draconic support in the config till they have a fix.

**Comment by vrork** [comment]
can confirm
https://pastebin.com/uFWr14CA

**Comment by MokahTGS** [comment]
Yup...same.  https://pastebin.com/BerqyVqu

**Comment by Landmaster** [comment]
I honestly cannot reproduce this. Anyway, with the latest dev build it seems to work, but I honestly don't know how the hell such a crash would arise, because the exact same variable is always being referenced. Whatever… -_-

**Comment by DeadSix27** [comment]
@Landmaster why the thumbs down reaction?

**Comment by Landmaster** [comment]
@DeadSix27 

> I honestly don't know how the hell such a crash would arise, **because the exact same variable** *[emphasis added]* is always being referenced.

…and according to the source code that has not changed.

 @DeadSix27 @blockbreaker1361 @Protheus @vrork @MokahTGS I released PlusTiC 5.0.1.2 which seems to work with the latest Draconic Evolution (2.1.0.232), but the cause of the crash is still ***very*** unclear, so I will not remove the "can't reproduce" tag just yet.

**Comment by DeadSix27** [comment]
@Landmaster Ah I just misunderstood the reaction then, thought you disliked my issue report or something about it..

**Comment by Landmaster** [comment]
@DeadSix27 I think I figured out why Draconic Evolution was crashing like it did. @brandon3055 changed the field type from plain `Item` to `ItemCore`, messing everything up.

**Comment by DeadSix27** [comment]
@Landmaster Suprised java didn't complain, unless itemcore is inheriting Item ?

**Comment by Landmaster** [comment]
@DeadSix27 `ItemCore` apparently does inherit from `Item`, but Java still seems to cries foul about these things anyway.

**Comment by DeadSix27** [comment]
@Landmaster ye idk, I never got that much into java.
