### ISSUE TITLE
Crash with latest version 5.0.1.4

### ISSUE THREAD

**Issue by blockbreaker1361** [Landmaster/PlusTiC#51]
https://pastebin.com/mB4W8EmA
I just got this crash with the latest version.

**Comment by TheThingG** [comment]
Temp fix: downgrade chisel to 2-0.0.10.22 and remove CTM-lib

**Comment by Landmaster** [comment]
@blockbreaker1361 @TheThingG It looks like there is a problem (most likely an API change) with some of the classes in Chisel. PlusTiC is just tripping over the bomb that Chisel set (i.e. this seems to be an EnderIO/Chisel issue).

**Comment by Landmaster** [comment]
@blockbreaker1361  @TheThingG fixed by Chisel
