### ISSUE TITLE
PlusTIC Crash upon loadup

### ISSUE THREAD

**Issue by ElectricBlue1** [Landmaster/PlusTiC#52]
I recently updated PlusTIC to 5.0.1.4 on 1.10 and the pack i'm running it on is a custom and hasn't crash with this mod in particular until this update. Here the log https://pastebin.com/xbwN57TJ

**Comment by Landmaster** [comment]
duplicate of #51

**Comment by Landmaster** [comment]
@ElectricBlue1 **Update Chisel.**
