### ISSUE TITLE
Crash on ticking player on Nick of Time trying to activate

### ISSUE THREAD

**Issue by Lycanic** [Landmaster/PlusTiC#53]
[Playing on foolcraft 1.4.5 with a applied energistics added, and avarita updated]

When Nick of Time attempts to activate, it causes a crash to launcher. It continues to cause this crash on world load until player file is replaced/deleted (though if you're unlucky it may continue anyway, up until now I'd been fine by replacing with an old version but it's keeping crashing now).

I've recreated this in the latest version (so found in both 5.0.1.3 & 5.0.1.4), in a new world by spawning a new nickel tool and a stack of ender pearls, linking to my spawn location and drowning.

Here's the crash report in its entirety https://pastebin.com/ugbCPVtd
What I believe is relevant is:
java.lang.NoSuchMethodError: net.minecraft.block.state.IBlockState.func_185890_d(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/util/math/AxisAlignedBB;
	at landmaster.plustic.util.Utils.canTeleportTo(Utils.java:175)
	at landmaster.plustic.traits.NickOfTime.timing(NickOfTime.java:41)
The location in the new world was just on grass, in the other it is a flat colored block (but in previous versions teleported fine)

**Comment by Landmaster** [comment]
@Lycanic Fixed in 5.0.1.5

**Comment by Lycanic** [comment]
Thanks for fixing so fast, you're absolutely amazing!
