### ISSUE TITLE
Modifier JSON loading

### ISSUE THREAD

**Issue by Claycorp** [Landmaster/PlusTiC#56]
https://pastebin.com/qkgNWRYM

That 95 times is really unneeded. Can you please fix this?

**Comment by Landmaster** [comment]
@Claycorp This is due to the fact that I haven't added the modifier textures yet. Those will be added gradually.

**Comment by Landmaster** [comment]
@Claycorp It turned out that too many modifier jsons were being registered—the code would try to register the trait models, also! The errors will be fixed in 5.2.1.0. As for modifier textures, they will come…eventually.
