### ISSUE TITLE
Crash after updating PlusTiC and Draconic Evolution

### ISSUE THREAD

**Issue by zackeezy** [Landmaster/PlusTiC#57]
PlusTiC version: 4.4.0.0
MC Version: 1.10.2
Forge Version: 12.18.3.2254
Draconic Evolution version: 2.1.1
crash log: https://pastebin.com/Qf4YeXZS

**Comment by Landmaster** [comment]
@zackeezy Update to 5.0.1.5.

**Comment by zackeezy** [comment]
Curse listed it as a 1.11.2 mod so I wasn't sure if it was also for 1.10.2

**Comment by Landmaster** [comment]
@zackeezy It is for both versions. CurseForge displays this correctly, but not Curse.

**Comment by zackeezy** [comment]
Okay well I was checking Curse, not CurseForge.  my bad.
