### ISSUE TITLE
advance rocketry issues

### ISSUE THREAD

**Issue by robjw95** [Landmaster/PlusTiC#58]
Advanced rocketry support does not seem to be  working.  I tried it in my custom modpack as well as the bare minimum of mods in a test pack(just plustic, tinkers , advanced rocketry and jei) and it still did not add the iridium or titanium.

**Comment by Landmaster** [comment]
Which versions of the mods are you using?

**Comment by robjw95** [comment]
they were the most current on the twitch/curse launcher listed for 1.11.2
if you need the detailed modlist I can post that later

**Comment by Landmaster** [comment]
Fixed in 5.1.0.0
