### ISSUE TITLE
Duplication with Global Traveler

### ISSUE THREAD

**Issue by pip69** [Landmaster/PlusTiC#6]
Not sure if it can happen with a simpler method, but this is what happens for me:

excavator with **alumite** plate, copper tough rod, titanium binding, bronze head
added abilities **hammered** & mending moss 2
iron backpack with **filter** & compression upgrade

so when I use the excavator on sand to be able to get dust from the hammered ability, the dust would be collected by the backpack, but the linked chest would also get the sand

side note, can Global Traveler be only linked to inventory using shift right click?

**Comment by Landmaster** [comment]
Which mod is the backpack from?

**Comment by Landmaster** [comment]
@pip69 What mod is the hammered ability from?

**Comment by pip69** [comment]
I'd added this to modpack Forever Stranded. 
Iron backpack mod
Hammered is from one of the ex milo mods. Can't look it up at the moment, but its one of the ones in the modpack.

**Comment by Landmaster** [comment]
Looking at the source code of Ex Nihilo Omnia, it seems that Global Traveler's event is called before Hammering's event, whereas it should be called after (in order for Global Traveler to pick up Hammering's drops). I'll check if that fixes the duplication issue, and if so, this issue can be considered resolved.
