### ISSUE TITLE
Survivalist rock ores to smeltery

### ISSUE THREAD

**Issue by Seth0067** [Landmaster/PlusTiC#60]
With Modtweaker 1.11.2 offline in terms of Tcon support - you are the only game in town!  

Survivalist mod adds "rock ores" in place of normal ore drops that return 1 nugget per rock ore when placed in a vanilla furnace.  Would be nice to see these melt to 2x nuggets when placed inside the smeltery.

Here's my aborted/nonworking modtweaker scripts in case that helps:
//mods.tconstruct.Smeltery.addMelting(<tconstruct:molten_gold> * 2, <survivalist:rock_ore:1>, 532);
//mods.tconstruct.Smeltery.addMelting(<tconstruct:molten_copper> * 2, <survivalist:rock_ore:2>, 542);
//mods.tconstruct.Smeltery.addMelting(<tconstruct:molten_tin> * 2, <survivalist:rock_ore:3>, 350);
//mods.tconstruct.Smeltery.addMelting(<tconstruct:molten_lead> * 2, <survivalist:rock_ore:4>, 400);
//mods.tconstruct.Smeltery.addMelting(<tconstruct:molten_silver> * 2, <survivalist:rock_ore:5>, 480);
//mods.tconstruct.Smeltery.addMelting(<tconstruct:molten_iron> * 2, <survivalist:rock_ore:0>, 769);

**Comment by Landmaster** [comment]
Added in 5.1.2.0
