### ISSUE TITLE
1.10.2 crash "The name to be added to the registry is null"

### ISSUE THREAD

**Issue by ASpieler** [Landmaster/PlusTiC#61]
Added PlusTIC 5.1.2 to our tweaked Skyfactory3 server, got a crash: [https://pastebin.com/wZsws1g9](https://pastebin.com/wZsws1g9)
removed PlusTIC and it starts fine, tried downgrading to 5.1.1, then 5.1.0, both get exactly the same exception. Given that nothing else knows PlusTIC exists and tries to add items/blocks/fluids/whatever when it is present, I'm guessing this exception is coming from PlusTIC. Unfortunately, I can't make heads or tails of it, hence this issue being opened instead of you getting a pull request.
If you need any information from me to help in finding the issue, I'm more than happy to help, run tests, whatever needs to happen.

**Comment by ASpieler** [comment]
update:
disabled integration for:
Actually Additions
Advanced Rocketry
ArmorPlus
Avaritia
Botania
Galacticraft
Land Craft
LandCore
Substratum
Survivalist

and now the server starts fine, most of those were disabled as a precaution, as we don't have most of them in the pack, actually additions was disabled more as a personal preference, and botania was disabled due to the note on the Natural Pledge option, which was also disabled.

**Comment by Landmaster** [comment]
@ASpieler Strange, sounds like some weird mod interaction is happening, since PlusTiC does nothing special with the Forge registries. Try removing some of the other mods in groups, and find the smallest set of mods that causes this crash.

**Comment by ASpieler** [comment]
First, i think I'll re-enable the things i turned off, as with them off it runs fine, and disable them one at a time and see which one(s) seem to be causing the issue. I'm wondering if some of the code to detect installed mods wasn't acting up.
If this doesn't produce results, then I'll start working with individual mods, as we have quite a few of them.

**Comment by ASpieler** [comment]
O.o wow, ok, so I just got around to shutting the server down to test this, and the very first thing I disable fixes the issue.
To test, i reset back to default config (after taking a backup of course), and tried starting the server, crash, then disabled Actually Additions support in the PlusTiC config, server starts fine, and is running beautifully.

If you would like i can send you a list/link/whatever with our mod set, or config files, or server logs, whatever you need to narrow this down, because apparently the AA integration has an issue.
Granted, this may be a version issue, so here's the relevant info:
Actually Additions 1.10.2-r105
PlusTiC 5.1.2.0
Forge 1.10.2-12.18.3.2281

**Comment by ASpieler** [comment]
My apologies for taking your time with an issue that it is now fairly apparent has nothing to do with your mod. As the server is now actually informing me of what mods are erroring, I now have a lead on this, and it isn't, so far as I can tell actually coming from this mod.
For posterity/interested parties, the erroring mods are AE2 and FTBLib.

Given the above, I'm closing this issue.
