### ISSUE TITLE
Psicological trait not working

### ISSUE THREAD

**Issue by swyrl** [Landmaster/PlusTiC#64]
^ Title. I have the psicological trait on two tools. I am lvl 20+ in psi and have a CAD in my inventory,  but my tools still aren't healing, even a little. Using PlusTIC 5.1.2.0 and Psi r1.1-47 on 1.11.2 (forge 13.20.1.2393)

As a side note, I can put the 'mana' trait on the tools no problem and that works fine.

**Comment by Landmaster** [comment]
Fixed in 5.2.0.0
