### ISSUE TITLE
[1.10.2] PlusTiC referencing EntityAIWanderAvoidWater which is present in 1.11.2 but absent in 1.10.2

### ISSUE THREAD

**Issue by Semajor** [Landmaster/PlusTiC#66]
When I update from 5.1.3.0 to 5.2.0.0 my single player worlds are getting stuck at the Building World screen. The game isn't generating a crash report unfortunately because I have to go into task manager to end the Java process and kill it. I'm running a modified version of the Foolcraft pack with the mods/versions in the included text file. If you need any additional information, or have steps I should take to create a crash log, please let me know.

[Foolcraft Custom Modlist.txt](https://github.com/Landmaster/PlusTiC/files/1145488/Foolcraft.Custom.Modlist.txt)

P.S. Really love the work you've done on this mod, and thank you SO much for making the updated Natural Pledge work on 1.10.2 again!

**Comment by Landmaster** [comment]
@Semajor Do you have a **logs/latest.log** file in your Minecraft directory? That probably contains the details of the problem, even if no crash report is generated.

**Comment by Semajor** [comment]
Sure thing, here's a file with just the most recent attempt to load the world. Looks like it's getting a conflict with More Player Models and throwing an exception, then getting stuck on the world unloading. Disabling MPM lets the world load again, so for the time being I can just run without that turned on until you can decipher what the precise cause is. Error text starts on line 7463 to save you a bit of hunting.

[latest.txt](https://github.com/Landmaster/PlusTiC/files/1145769/latest.txt)

**Comment by Landmaster** [comment]
@Semajor From the logs, it appears to be some problem specific to More Player Models (I'm guessing a mod loading problem) unrelated to PlusTiC. Unfortunately, since More Player Models is not visible-source (as far as I know), the cause is not evident to others. Report it to More Player Models' issue tracker, and come back here when there is a response from them.

**Comment by Semajor** [comment]
So I wanted to provide an update to you on this issue since I've gotten a response from Noppes over on the MPM side. Noppes just updated MPM over the weekend, and it's still crashing with the exact same error. The game runs perfectly on 5.1.3.0 of PlusTiC, and breaks with any of the updated versions.

[This is the code](https://minecraft.curseforge.com/projects/more-player-models/issues/12) causing the problem, and it's only when PlusTiC is updated to a version past 5.1.3.0 (this includes 5.2.0.0, 5.2.0.1, and 5.2.1.0). Is it possible that the updates to make mana/psicological work properly are running living entity checks and causing MPM to just freak out?

**Comment by Semajor** [comment]
Just tried generating a new world with only those mods installed with the latest versions. Got exactly the same error, downgraded to PlusTiC 5.1.3.0 and it loaded into the world. Here's the log file from that attempt for you.

[071817_latest.txt](https://github.com/Landmaster/PlusTiC/files/1156167/071817_latest.txt)

This error just makes no sense at all though as far as what's causing it, since I can't think of anything in either mod that should be affecting entity AI.

**Comment by Landmaster** [comment]
@Semajor @noppes See my comment [in the MPM issue tracker](https://minecraft.curseforge.com/projects/more-player-models/issues/12).

**Comment by Landmaster** [comment]
@Semajor @Noppes I might have figured out the cause of the crash. It turned out that `EntityAIWanderAvoidWater`, which PlusTiC uses for one of its entities (`EntitySupremeLeader`) and is present in 1.11.2, is, for some reason, *completely* absent in 1.10.2! I will push and release a fix soon.

**Comment by Landmaster** [comment]
@Semajor @Noppes Fixed in 5.2.1.1

**Comment by Semajor** [comment]
Sweet, sweet bug fixes. Thanks again!
