### ISSUE TITLE
[1.10.2-5.2.1.0] Disabling Laser Gun does not remove its parts from Stencil Table

### ISSUE THREAD

**Issue by Compegen** [Landmaster/PlusTiC#68]
When the laser gun is disabled, its parts can still be built in a stencil table, causing it to give an invalid stencil. 
____________
This does not happen with the Katana when it is disabled.
____________
![capture](https://user-images.githubusercontent.com/8009507/28283549-a4392a9c-6af3-11e7-88b1-ce7f5ef3c16b.PNG)

**Comment by Landmaster** [comment]
Fixed in 5.2.1.1
