### ISSUE TITLE
Draconic tool parts

### ISSUE THREAD

**Issue by TheClinery1** [Landmaster/PlusTiC#69]
I have tried to make the draconic tool parts and there is no way to make them, I cant smelt the draconium in the smeltery and no way to use the part builder. I am using DE 1.10.2-2.1.2.245 and PlusTiC 5.2.1.0

**Comment by Landmaster** [comment]
@TheClinery1 Check the Tinkers book; it is not a smeltery item. Use the wyvern/awakened cores.

**Comment by Landmaster** [comment]
@TheClinery1 It's also a duplicate of #29.
