### ISSUE TITLE
[1.12] Crash on startup

### ISSUE THREAD

**Issue by billybricker** [Landmaster/PlusTiC#70]
Title. 

Forge: 14.21.1.2415
Mantle: 1.12-1.3.0.15
TiC: 1.12-2.7.1.9
PlusTiC: 6.0.0.0

Crash-log: https://pastebin.com/vWnvXf62

**Comment by Landmaster** [comment]
fixed in 6.0.0.1

**Comment by billybricker** [comment]
sweet, thanks. I'll update after work.
