### ISSUE TITLE
Crash on Startup: 1.10.2 Heavily modified FTB Beyond

### ISSUE THREAD

**Issue by ReportBot9009** [Landmaster/PlusTiC#72]
Not sure what else to say than added this to my heavily modified FTB Beyond pack running on MultiMC and this crashed on load.

https://paste.ee/p/pNuGM

**Comment by Landmaster** [comment]
@ReportBot9009 That game ran an *extremely outdated* version of PlusTiC. Update to at least 5.2.1.0, as that supports both 1.10.2 and 1.11.2. Your issue was fixed a *long* time ago.
