### ISSUE TITLE
Caught exception from PlusTiC (plustic)

### ISSUE THREAD

**Issue by trilexcom** [Landmaster/PlusTiC#75]
hi LandMaster

MC 1.12 Forge # 2418 Tinkers Contruct : 1.12-2.7.1.9

i tried to add PlusTic to our modpack we are getting a error msg 

here is the pastebin https://pastebin.com/H30tHffN 

please let me know if its plustic issues or another mod is causing that 

Thanks 

Mat (TrilexCom)

**Comment by Landmaster** [comment]
duplicate of #74
