### ISSUE TITLE
[1.12] Crash on startup

### ISSUE THREAD

**Issue by NillerMedDild** [Landmaster/PlusTiC#76]
Hey!

[Crashlog](https://pastebin.com/miHrhd3q)
The game crashes on startup, as far as I can see it's because of a duplicate oredict entry,
made by PlusTiC and vanilla TiC.

Minecraft 1.12
Forge 1.12-14.21.1.2415
PlusTiC 6.0.0.2
TiC 1.12-2.7.1.9

**Comment by Landmaster** [comment]
@NillerMedDild Cannot reproduce; try to find the smallest set of mods that causes this crash.

**Comment by Landmaster** [comment]
@NillerMedDild Also, see if [this release](https://github.com/Landmaster/PlusTiC/releases/tag/6.0.0.3) might fix the problem.

**Comment by NillerMedDild** [comment]
Yup, that fixed it, thanks 👍
