### ISSUE TITLE
Terrasteel bow doesnt shoot with mana ring in inventory

### ISSUE THREAD

**Issue by Aanika** [Landmaster/PlusTiC#77]
I have a Terrasteel-Mirion cobalt string longbow with the modifiers reinforced III and hastester if i have a greater mana ring in my inventory it wont fully draw and shoot it draws a very little over and over and over and drains the ring mana very quickly when i try to shoot it.

**Comment by yepidoodles** [comment]
This is my server:
Minecraft: 1.10.2
Forge: 2316
SpongeForge: API 5.2.0 v2407
Tinkers' Construct: 2.6.5
PlusTiC: 5.1.2.0
Tinker Tool Leveling: 1.0.1
Happy to provide other details if requested.

**Comment by Landmaster** [comment]
Update PlusTiC to at least 5.2.1.1.
