### ISSUE TITLE
Crash during load with Thermal Foundation (1.12)

### ISSUE THREAD

**Issue by Ushupiuck** [Landmaster/PlusTiC#79]
The tittle says everything. You guys need to update the integration module 😛 
[crash-2017-07-26_18.22.15-client.txt](https://github.com/Landmaster/PlusTiC/files/1178198/crash-2017-07-26_18.22.15-client.txt)
thanks for reading!

**Comment by Landmaster** [comment]
@Ushupiuck Cannot reproduce this with the latest versions of the mods. Try updating Thermal Foundation to at least 2.3.3.10, and try seeing [if the version of PlusTiC I just released](https://github.com/Landmaster/PlusTiC/releases/tag/6.0.0.4) works.

**Comment by Ushupiuck** [comment]
...Not my fault if you reply & test, **after** releasing the fix -.-
aka you fixed it without even noticing. you silly!

**Comment by Landmaster** [comment]
Strange, this bug is appearing sporadically and unpredictably even in the latest versions. I'll have to move to alloy/pyrotheum fuel code to `init2`.
