### ISSUE TITLE
[Request] Disabling from specific materials

### ISSUE THREAD

**Issue by accessdenied0** [Landmaster/PlusTiC#84]
Hello @Landmaster ,

I would like to use your mod together with another mod which adds also a view materials with modifier: moartinkers.

Now because these two mods are so alike they add both same materials and this naturally crashes. Now I want to keep the most interesting ones of both of these mods. The only problem is your mod only allows to disable whole "mod supports" and this includes a few materials I would like to keep. E.g. Thermal Foundation.

My request is to add a possibility to disable or black-list each material for itself, to prevent crashes and allow to use both mods.

**Comment by Landmaster** [comment]
@accessdenied0 This will come to 1.12, but not 1.11 and earlier.

**Comment by Landmaster** [comment]
Added in 6.0.4.0 and later
