### ISSUE TITLE
crash upon adding armory mod 

### ISSUE THREAD

**Issue by Miner94** [Landmaster/PlusTiC#89]
works well until i add the Thermal smeltery mod 
For minecraft 1.10.2

**Comment by Landmaster** [comment]
@Miner94 Do you have a log file?

**Comment by Miner94** [comment]
i can get one but i have no idea where to put it

**Comment by Landmaster** [comment]
@Miner94 Put it in a [pastebin.](https://pastebin.com/)

**Comment by Miner94** [comment]
here it is

https://pastebin.com/PaDKGqMi

**Comment by Landmaster** [comment]
@Miner94 This is a materials conflict with Moar Tinkers, which was created after PlusTiC and has very similar functionality, except that Moar Tinkers does not have any new tools at this time. Disable the ProjectE materials for either PlusTiC or Moar Tinkers.

**Comment by Miner94** [comment]
ok how would i go about disabeling that
