### ISSUE TITLE
Lasergun not shooting entities but breaks cobblestone to stone

### ISSUE THREAD

**Issue by WhiskersWatson** [Landmaster/PlusTiC#90]
Just updated the mod and looked at the source a bit, it seems whatever you did to add block vaporizing is broken. or maybe its just circumstance regardless heres my pastebin https://pastebin.com/YgS6mwne The error only happens when i right click with the lasergun.

If you need anymore information let me know.
Hope i could help.

**Comment by WhiskersWatson** [comment]
Should probably also mention this is on a server.

**Comment by Landmaster** [comment]
@WhiskersWatson Fixed in 6.0.1.1
