### ISSUE TITLE
Add the remaining Natura woods and Actually Additions gems

### ISSUE THREAD

**Issue by Landmaster** [Landmaster/PlusTiC#93]
- [x] Restonia
- [x] Palis
- [x] Emeradic
- [x] Diamatine
- [x] Ghostwood
- ~~[ ] Bloodwood~~ (Not yet added by Natura)
- [x] Fusewood

**Comment by belathus** [comment]
Don't we have bloodwood now? Pretty sure I've grabbed a sapling or 300 in my current world.
